import { DomainValidationError } from './errors.ts';
import { BIDI_CONTROLS, INVISIBLE_OR_INVALID_CHARS } from './text.ts';
import { UUID_V4 } from './user.ts';

/**
 * Document files (steps.md 16.1): the files a Document holds. The uploaded file — the **original** —
 * is kept byte-for-byte, including embedded metadata, and is only ever handed out as a download.
 * **Previews** and **thumbnails** are derived from it: inert, metadata-free JPEGs that can be made again
 * and are never called or served as the original. Sizes are decimal (1 MB = 1 000 000 bytes), as in 14.3.
 */
export type DocumentFileId = string & { readonly __brand: 'DocumentFileId' };

/** The accepted formats, identified from the content — never from the file name or the declared type. */
export const DOCUMENT_FILE_FORMATS = ['PDF', 'JPEG', 'PNG', 'HEIC'] as const;
export type DocumentFileFormat = (typeof DOCUMENT_FILE_FORMATS)[number];

/** The only content types an original is ever served with, and the extension a download name ends in. */
export const DOCUMENT_FILE_TYPES: Readonly<Record<DocumentFileFormat, { readonly contentType: string; readonly extension: string; readonly extensions: readonly string[] }>> =
  Object.freeze({
    PDF: { contentType: 'application/pdf', extension: 'pdf', extensions: ['pdf'] },
    JPEG: { contentType: 'image/jpeg', extension: 'jpg', extensions: ['jpg', 'jpeg', 'jpe', 'jfif'] },
    PNG: { contentType: 'image/png', extension: 'png', extensions: ['png'] },
    HEIC: { contentType: 'image/heic', extension: 'heic', extensions: ['heic', 'heif'] },
  });

/** Largest accepted file unless the instance admin chose another limit (H8). */
export const DEFAULT_MAX_DOCUMENT_FILE_BYTES = 50_000_000;
/** What the instance admin may choose: files are parsed in memory for previews, so the limit stays bounded. */
export const DOCUMENT_FILE_BYTES_RANGE = Object.freeze({ min: 1_000_000, max: 100_000_000 });
/** Largest decoded image (width × height), as for instruction images. */
export const MAX_DOCUMENT_IMAGE_PIXELS = 50_000_000;
/** Pages of a PDF that get a preview; later pages are read from the downloaded original. */
export const MAX_PDF_PREVIEW_PAGES = 500;
/** Longest edge of a preview page: an A4 page keeps more than 200 px per inch, so small print stays readable when zoomed. */
export const PREVIEW_MAX_EDGE = 2400;
/** PDF pages are drawn at this resolution (and never beyond `PREVIEW_MAX_EDGE`). */
export const PDF_PREVIEW_DPI = 200;
/** Longest edge of a thumbnail. */
export const THUMBNAIL_MAX_EDGE = 400;
export const MAX_ORIGINAL_NAME_LENGTH = 255;

/** One combined storage limit per Workspace (H7, P1): a usage limit — no disk space is reserved. */
export const DEFAULT_WORKSPACE_STORAGE_BYTES = 5_000_000_000;

/** How far the previews of a file are: made in the background after the upload. */
export const PREVIEW_STATES = ['PENDING', 'READY', 'PARTIAL', 'FAILED', 'NONE'] as const;
export type PreviewState = (typeof PREVIEW_STATES)[number];

export const DERIVATIVE_KINDS = ['THUMBNAIL', 'PREVIEW'] as const;
export type DerivativeKind = (typeof DERIVATIVE_KINDS)[number];

export function parseDocumentFileId(value: string): DocumentFileId {
  if (!UUID_V4.test(value)) throw new DomainValidationError('file', 'invalid_document_file_id', 'File id must be a lower-case UUIDv4');
  return value as DocumentFileId;
}

/**
 * The name a file was uploaded with, kept as data only: it is shown, exported and offered again as the
 * download name, and never becomes a storage path. Any directory part is dropped; the rest is NFC text
 * of 1–255 code points without control, invisible or bidi characters (as email addresses, 12.4).
 */
export function normalizeOriginalFileName(input: string): string {
  const base = input.slice(Math.max(input.lastIndexOf('/'), input.lastIndexOf('\\')) + 1);
  const name = base.trim().normalize('NFC');
  if (name.length === 0 || name === '.' || name === '..') throw new DomainValidationError('name', 'file_name_empty', 'A file name is required');
  if ([...name].length > MAX_ORIGINAL_NAME_LENGTH) throw new DomainValidationError('name', 'file_name_too_long', 'The file name is too long');
  if (INVISIBLE_OR_INVALID_CHARS.test(name) || BIDI_CONTROLS.test(name)) {
    throw new DomainValidationError('name', 'file_name_invalid_characters', 'The file name contains invisible or control characters');
  }
  return name;
}

/** Characters that never appear in a generated download name (path separators, quotes, shell and Windows-reserved ones). */
const UNSAFE_DOWNLOAD_CHARS = /[\\/:*?"<>|;%\p{Cc}]/gu;
const WINDOWS_RESERVED = /^(con|prn|aux|nul|com[0-9]|lpt[0-9])$/i;

/**
 * The name offered for a download, generated by the server from the stored name and the **detected**
 * format: no path, no reserved or control characters, at most 120 characters, and always ending in an
 * extension of that format — `invoice.html` uploaded as a JPEG downloads as `invoice.html.jpg`.
 */
export function downloadFileName(originalName: string, format: DocumentFileFormat): string {
  const type = DOCUMENT_FILE_TYPES[format];
  const name = originalName.replace(UNSAFE_DOWNLOAD_CHARS, '_').replace(/^[.\s]+|[.\s]+$/g, '');
  const dot = name.lastIndexOf('.');
  const extension = dot > 0 ? name.slice(dot + 1).toLowerCase() : '';
  let stem = type.extensions.includes(extension) ? name.slice(0, dot) : name;
  const suffix = type.extensions.includes(extension) ? name.slice(dot + 1) : type.extension;
  stem = [...stem].slice(0, 120 - suffix.length - 1).join('').replace(/[.\s]+$/g, '');
  if (stem.length === 0 || WINDOWS_RESERVED.test(stem.split('.')[0] ?? '')) stem = `file${stem.length === 0 ? '' : `-${stem}`}`;
  return `${stem}.${suffix}`;
}

/** The limit an instance admin sets for one file. */
export function parseMaxDocumentFileBytes(bytes: number): number {
  if (!Number.isInteger(bytes) || bytes < DOCUMENT_FILE_BYTES_RANGE.min || bytes > DOCUMENT_FILE_BYTES_RANGE.max) {
    throw new DomainValidationError('documentMaxFileBytes', 'invalid_document_file_limit', 'Choose a limit between 1 MB and 100 MB');
  }
  return bytes;
}

/**
 * The formats an instance admin allows: a non-empty subset of the formats the server can validate —
 * the list can be narrowed, never widened. Returned in the canonical order without duplicates.
 */
export function parseDocumentFormats(formats: readonly string[]): DocumentFileFormat[] {
  const unknown = formats.some((format) => !(DOCUMENT_FILE_FORMATS as readonly string[]).includes(format));
  if (unknown || formats.length === 0) {
    throw new DomainValidationError('documentFormats', 'invalid_document_formats', 'Choose at least one of PDF, JPEG, PNG and HEIC');
  }
  return DOCUMENT_FILE_FORMATS.filter((format) => formats.includes(format));
}

/** Whether storing `adding` more bytes stays within the Workspace's limit. A full Workspace still reads everything. */
export function fitsStorage(usedBytes: number, addingBytes: number, limitBytes: number): boolean {
  return usedBytes + addingBytes <= limitBytes;
}

/** How many of a PDF's pages get a preview. */
export function previewPageCount(format: DocumentFileFormat, pageCount: number | null): number {
  if (format !== 'PDF') return 1;
  return pageCount === null ? 0 : Math.min(pageCount, MAX_PDF_PREVIEW_PAGES);
}
