import { Readable } from 'node:stream';
import {
  documentStorageUsage,
  getDocumentFile,
  openDerivative,
  openOriginal,
  uploadDocumentFile,
  type DocumentFileRecord,
  type DocumentStorageUsage,
  type OpenedFile,
} from '@vergissmeinnicht/application';
import { DOCUMENT_FILE_BYTES_RANGE, MAX_PDF_PREVIEW_PAGES, UUID_V4, type WorkspaceId } from '@vergissmeinnicht/domain';
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { z } from 'zod';
import type { AppServices } from '../composition.ts';
import { InvalidRequestError } from './errors.ts';
import { requireUser, type Principal } from './session.ts';

const MINUTE_MS = 60_000;
/** How much of a refused upload is still read (and thrown away) so that the answer arrives. */
const MAX_DISCARDED_BYTES = 32_000_000;
const uuid = z.string().regex(UUID_V4);
const workspaceParams = z.strictObject({ workspaceId: uuid });
const fileParams = z.strictObject({ workspaceId: uuid, fileId: uuid });
const pageParams = z.strictObject({ workspaceId: uuid, fileId: uuid, page: z.string().regex(/^[1-9][0-9]{0,2}$/) });
const noQuery = z.strictObject({});

/**
 * `X-File-Name`: the file's name, percent-encoded UTF-8 (a header value cannot carry it otherwise).
 * A missing or malformed header is an empty name, which the domain refuses — after authorization.
 */
function fileNameOf(request: FastifyRequest): string {
  const header = request.headers['x-file-name'];
  if (typeof header !== 'string' || header.length > 3072) return '';
  try {
    return decodeURIComponent(header);
  } catch {
    return '';
  }
}

function parse<T>(schema: z.ZodType<T>, value: unknown): T {
  const parsed = schema.safeParse(value);
  if (!parsed.success) throw new InvalidRequestError();
  return parsed.data;
}

function principalOf(request: FastifyRequest): Principal {
  if (request.principal === null) throw new Error('requireUser did not run');
  return request.principal;
}

/** Used and limit of the Workspace's combined storage (16.4); the breakdown by tool is for Workspace admins (`…/storage`). */
const usageView = (usage: DocumentStorageUsage) => ({ usedBytes: usage.used, limitBytes: usage.limit });

/** What a member sees of a file: never its storage name (hash) and no user ids. */
export const fileView = (file: DocumentFileRecord) => ({
  id: file.id,
  name: file.originalName,
  format: file.format,
  bytes: file.bytes,
  pageCount: file.pageCount,
  width: file.width,
  height: file.height,
  passwordProtected: file.encrypted,
  activeContent: file.activeContent,
  preview: {
    state: file.previewState,
    pages: file.previewPages,
    // Why a file has no preview at all: its format has none (HEIC, for now) or it is password-protected.
    unavailable: file.previewState !== 'NONE' ? null : file.encrypted ? 'password_protected' : 'format',
  },
  uploadedBy: file.uploadedByName,
  uploadedAt: file.uploadedAt.toISOString(),
});

/** RFC 6266 / 5987: an ASCII fallback plus the UTF-8 name; the name was generated by the server. */
export function attachment(fileName: string): string {
  const fallback = fileName.replace(/[^\x20-\x7e]/g, '_').replace(/["\\]/g, '_');
  return `attachment; filename="${fallback}"; filename*=UTF-8''${encodeURIComponent(fileName).replace(/['()*]/g, (c) => `%${c.charCodeAt(0).toString(16).toUpperCase()}`)}`;
}

function send(reply: FastifyReply, file: OpenedFile, disposition: string) {
  return reply
    .type(file.contentType)
    .header('Content-Length', file.bytes)
    .header('Content-Disposition', disposition)
    .send(Readable.from(file.stream));
}

/**
 * Files of Documents (16.1). An upload is the raw file as the request body (`application/octet-stream`,
 * streamed to the data volume while it is counted — never buffered in memory); its name travels as
 * data in the `X-File-Name` header, not in the address, so it reaches no access log. The server identifies and validates the content
 * and keeps the **original unchanged**. Originals are only ever sent as downloads
 * (`Content-Disposition: attachment`, the content type of the detected format, `nosniff`, a `sandbox`
 * policy); previews and thumbnails are derived JPEGs. Everything needs a session and `document.view`
 * (or `document.manage` to upload) in that Workspace, and the Documents tool switched on there (404 otherwise): an id of another Workspace is "not found", and
 * the storage name of a file is never accepted.
 */
export async function documentFileRoutes(app: FastifyInstance, { services }: { services: AppServices }) {
  const deps = services.documentFiles;
  app.addHook('preHandler', requireUser(services));
  // The body is handed on as a stream; the size limit is enforced while it is received (the instance
  // setting, at most `DOCUMENT_FILE_BYTES_RANGE.max`). Other content types are not parsed here at all.
  app.addContentTypeParser('application/octet-stream', (_request, payload, done) => done(null, payload));
  // A refused upload may still be arriving. So that the client receives the reason (and not a broken
  // connection), a bounded rest of the body is read and thrown away; beyond that the connection is closed.
  app.addHook('onSend', async (request, reply) => {
    const body = request.raw;
    if (request.method !== 'POST' || reply.statusCode < 400 || body.complete || body.destroyed) return;
    let discarded = 0;
    body.on('data', (chunk: Buffer) => {
      discarded += chunk.byteLength;
      if (discarded > MAX_DISCARDED_BYTES) body.destroy();
    });
    body.resume();
  });

  app.post(
    '/',
    {
      bodyLimit: DOCUMENT_FILE_BYTES_RANGE.max,
      config: {
        slowBody: true,
        rateLimit: {
          max: 300,
          timeWindow: 15 * MINUTE_MS,
          hook: 'preHandler',
          keyGenerator: (request: FastifyRequest) => `document-upload:${request.principal?.user.id ?? request.ip}`,
        },
      },
    },
    async (request, reply) => {
      const { workspaceId } = parse(workspaceParams, request.params);
      parse(noQuery, request.query);
      const name = fileNameOf(request);
      // Anything but raw bytes counts as an empty upload — after the authorization check.
      // Stopping early (a file above the limit) must not tear down the connection before the answer is sent.
      const source: AsyncIterable<Uint8Array> = request.body instanceof Readable ? request.body.iterator({ destroyOnReturn: false }) : Readable.from([]);
      const { file, usage } = await uploadDocumentFile(deps, { actor: principalOf(request).user, workspaceId: workspaceId as WorkspaceId, name, source });
      return reply.code(201).send({ file: fileView(file), usage: usageView(usage) });
    },
  );

  app.get('/usage', async (request) => {
    const { workspaceId } = parse(workspaceParams, request.params);
    return { usage: usageView(await documentStorageUsage(deps, { actor: principalOf(request).user, workspaceId: workspaceId as WorkspaceId })) };
  });

  app.get('/:fileId', async (request) => {
    const { workspaceId, fileId } = parse(fileParams, request.params);
    return { file: fileView(await getDocumentFile(deps, { actor: principalOf(request).user, workspaceId: workspaceId as WorkspaceId, fileId })) };
  });

  app.get('/:fileId/original', async (request, reply) => {
    const { workspaceId, fileId } = parse(fileParams, request.params);
    const file = await openOriginal(deps, { actor: principalOf(request).user, workspaceId: workspaceId as WorkspaceId, fileId });
    // Never rendered in the app's origin, whatever a browser makes of the bytes.
    reply.header('Content-Security-Policy', "sandbox; default-src 'none'");
    return send(reply, file, attachment(file.fileName));
  });

  app.get('/:fileId/thumbnail', async (request, reply) => {
    const { workspaceId, fileId } = parse(fileParams, request.params);
    const file = await openDerivative(deps, { actor: principalOf(request).user, workspaceId: workspaceId as WorkspaceId, fileId, kind: 'THUMBNAIL', page: 0 });
    return send(reply, file, 'inline; filename="thumbnail.jpg"');
  });

  // Pages are numbered from 1, as people count them.
  app.get('/:fileId/pages/:page', async (request, reply) => {
    const { workspaceId, fileId, page } = parse(pageParams, request.params);
    const number = Number(page);
    if (number > MAX_PDF_PREVIEW_PAGES) throw new InvalidRequestError();
    const file = await openDerivative(deps, { actor: principalOf(request).user, workspaceId: workspaceId as WorkspaceId, fileId, kind: 'PREVIEW', page: number - 1 });
    return send(reply, file, `inline; filename="page-${number}.jpg"`);
  });
}
