// Drizzle schema. Every change ships with a committed migration generated by `pnpm db:generate`.
//
// Auth-related tables follow Better Auth's core schema: Drizzle *property* names are the
// Better Auth field names (e.g. `name`, `emailVerified`), while *column* names are snake_case.
import { sql } from 'drizzle-orm';
import { check, foreignKey, index, integer, primaryKey, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';
import {
  CONTACT_KEY_KINDS,
  MAINTENANCE_STATUSES,
  CRITICAL_CONFIRM_MODES,
  KNOT_TARGET_TYPES,
  BUILT_IN_DOCUMENT_TYPES,
  DERIVATIVE_KINDS,
  DOCUMENT_FILE_FORMATS,
  LIST_KINDS,
  PREVIEW_STATES,
  WORKSPACE_TOOLS,
  PROCEDURE_ICONS,
  REASON_POLICIES,
  OCCURRENCE_STATES,
  RECURRENCE_KINDS,
  RECURRENCE_UNITS,
  RUN_STATES,
  SCHEDULE_KINDS,
  SCHEDULE_STATES,
  STEP_KINDS,
  STEP_STATES,
  THEME_PREFERENCES,
  USER_STATUSES,
  WORKSPACE_ROLES,
} from '@vergissmeinnicht/domain';

const timestampMs = (column: string) =>
  integer(column, { mode: 'timestamp_ms' })
    .notNull()
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`);

/**
 * Internal Users. `id` is the stable internal identity; login methods (password, TOTP,
 * future Apple/GitHub) are linked to it by separate tables and never replace it.
 */
export const users = sqliteTable(
  'users',
  {
    id: text('id').primaryKey(),
    /** Display name (Better Auth field `name`). */
    name: text('display_name').notNull(),
    /** Normalized email; see `normalizeEmail` in the domain package. */
    email: text('email').notNull().unique(),
    emailVerified: integer('email_verified', { mode: 'boolean' }).notNull().default(false),
    /** Better Auth core field. Not rendered anywhere until a reviewed use exists (see security.md §5). */
    image: text('image'),
    status: text('status', { enum: USER_STATUSES }).notNull().default('ACTIVE'),
    /** Server-wide admin flag (application-owned; must be `input: false` in Better Auth). */
    serverAdmin: integer('server_admin', { mode: 'boolean' }).notNull().default(false),
    createdAt: timestampMs('created_at'),
    updatedAt: timestampMs('updated_at'),
  },
  (table) => [
    // Defense in depth behind application-side validation.
    check('users_id_uuid', sql`length(${table.id}) = 36`),
    check('users_email_normalized', sql`${table.email} = lower(trim(${table.email})) and length(${table.email}) <= 254`),
    check('users_display_name_present', sql`length(trim(${table.name})) > 0`),
    check(
      'users_status_valid',
      sql.raw(`status in (${USER_STATUSES.map((status) => `'${status}'`).join(', ')})`),
    ),
  ],
);

/**
 * Better Auth sessions (model `session`, `modelName: 'sessions'`). The cookie carries
 * `token` plus an HMAC signature keyed by AUTH_SECRET, so the stored token alone cannot be
 * replayed as a cookie. Server-side state is authoritative: deleting the row ends the session.
 */
export const sessions = sqliteTable(
  'sessions',
  {
    id: text('id').primaryKey(),
    token: text('token').notNull().unique(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
    /** Client address as seen by the server (proxy trust per docs/development/security.md §11); never from client headers. */
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    createdAt: timestampMs('created_at'),
    updatedAt: timestampMs('updated_at'),
  },
  (table) => [index('sessions_user_id_idx').on(table.userId)],
);

/**
 * Better Auth accounts (model `account`, `modelName: 'accounts'`): linked authentication methods
 * of an internal User. `providerId = 'credential'` holds the Argon2id password hash; future
 * Apple/GitHub identities become further rows and never replace `users.id`.
 */
export const accounts = sqliteTable(
  'accounts',
  {
    id: text('id').primaryKey(),
    /** Provider subject. For `credential` it is the internal User id. */
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: integer('access_token_expires_at', { mode: 'timestamp_ms' }),
    refreshTokenExpiresAt: integer('refresh_token_expires_at', { mode: 'timestamp_ms' }),
    scope: text('scope'),
    /** Argon2id PHC string; only for `credential` rows. */
    password: text('password'),
    createdAt: timestampMs('created_at'),
    updatedAt: timestampMs('updated_at'),
  },
  (table) => [
    index('accounts_user_id_idx').on(table.userId),
    // One identity per provider subject: an external account can never be attached to two Users.
    uniqueIndex('accounts_provider_account_unique').on(table.providerId, table.accountId),
    check(
      'accounts_credential_shape',
      sql`${table.providerId} <> 'credential' or (${table.accountId} = ${table.userId} and ${table.password} like '$argon2id$%')`,
    ),
  ],
);

/**
 * Better Auth verification values (model `verification`, `modelName: 'verifications'`). Required
 * by Better Auth's schema check; no V1 flow writes to it (email verification and password reset
 * by email are disabled). Any future use must store only hashed or short-lived values.
 */
export const verifications = sqliteTable(
  'verifications',
  {
    id: text('id').primaryKey(),
    identifier: text('identifier').notNull(),
    value: text('value').notNull(),
    expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
    createdAt: timestampMs('created_at'),
    updatedAt: timestampMs('updated_at'),
  },
  (table) => [index('verifications_identifier_idx').on(table.identifier)],
);

/**
 * TOTP credentials, one per user. `secret` is sealed with AES-256-GCM (key from
 * DATA_ENCRYPTION_KEY, bound to the user id). `enabled_at IS NULL` = unconfirmed enrollment.
 */
export const totpCredentials = sqliteTable(
  'totp_credentials',
  {
    userId: text('user_id')
      .primaryKey()
      .references(() => users.id, { onDelete: 'cascade' }),
    sealedSecret: text('sealed_secret').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    enabledAt: integer('enabled_at', { mode: 'timestamp_ms' }),
    /** Replay protection: highest accepted RFC 6238 time step. */
    lastUsedStep: integer('last_used_step').notNull().default(-1),
    consecutiveFailures: integer('consecutive_failures').notNull().default(0),
    lockedUntil: integer('locked_until', { mode: 'timestamp_ms' }),
  },
  (table) => [
    check('totp_credentials_sealed_format', sql`${table.sealedSecret} like 'v1.%'`),
    check('totp_credentials_failures_non_negative', sql`${table.consecutiveFailures} >= 0`),
  ],
);

/** Single-use recovery codes; only SHA-256 hashes of the 80-bit codes are stored. */
export const recoveryCodes = sqliteTable(
  'recovery_codes',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => totpCredentials.userId, { onDelete: 'cascade' }),
    codeHash: text('code_hash').notNull().unique(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    usedAt: integer('used_at', { mode: 'timestamp_ms' }),
  },
  (table) => [
    index('recovery_codes_user_id_idx').on(table.userId),
    check('recovery_codes_hash_format', sql`length(${table.codeHash}) = 64`),
  ],
);

/**
 * Pending sign-ins of TOTP-enabled accounts (password verified, second factor outstanding).
 * The client holds the raw token in a cookie; only its SHA-256 hash is stored. No session exists
 * until the challenge is completed.
 */
export const mfaChallenges = sqliteTable(
  'mfa_challenges',
  {
    id: text('id').primaryKey(),
    tokenHash: text('token_hash').notNull().unique(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
    attempts: integer('attempts').notNull().default(0),
    consumedAt: integer('consumed_at', { mode: 'timestamp_ms' }),
  },
  (table) => [
    index('mfa_challenges_user_id_idx').on(table.userId),
    check('mfa_challenges_token_hash_format', sql`length(${table.tokenHash}) = 64`),
    check('mfa_challenges_expiry_after_creation', sql`${table.expiresAt} > ${table.createdAt}`),
  ],
);

/**
 * Admin- or operator-initiated account recoveries. Only a SHA-256 hash of the link token is stored;
 * the link goes to the account's own email address (or the operator's terminal).
 */
export const accountRecoveries = sqliteTable(
  'account_recoveries',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    tokenHash: text('token_hash').notNull().unique(),
    resetPassword: integer('reset_password', { mode: 'boolean' }).notNull(),
    resetTotp: integer('reset_totp', { mode: 'boolean' }).notNull(),
    /** NULL = issued by the operator CLI. */
    issuedByUserId: text('issued_by_user_id').references(() => users.id),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
    completedAt: integer('completed_at', { mode: 'timestamp_ms' }),
    revokedAt: integer('revoked_at', { mode: 'timestamp_ms' }),
  },
  (table) => [
    index('account_recoveries_user_id_idx').on(table.userId),
    check('account_recoveries_scope', sql`${table.resetPassword} = 1 or ${table.resetTotp} = 1`),
    check('account_recoveries_token_hash_format', sql`length(${table.tokenHash}) = 64`),
    check('account_recoveries_expiry_after_creation', sql`${table.expiresAt} > ${table.createdAt}`),
    check('account_recoveries_single_outcome', sql`${table.completedAt} is null or ${table.revokedAt} is null`),
    check('account_recoveries_not_self_issued', sql`${table.issuedByUserId} is null or ${table.issuedByUserId} <> ${table.userId}`),
  ],
);

/** Invitations. Only a SHA-256 hash of the link token is stored. */
export const invitations = sqliteTable(
  'invitations',
  {
    id: text('id').primaryKey(),
    email: text('email').notNull(),
    tokenHash: text('token_hash').notNull().unique(),
    grantsServerAdmin: integer('grants_server_admin', { mode: 'boolean' }).notNull().default(false),
    /** NULL = issued by the CLI bootstrap. */
    invitedByUserId: text('invited_by_user_id').references(() => users.id),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
    acceptedAt: integer('accepted_at', { mode: 'timestamp_ms' }),
    acceptedUserId: text('accepted_user_id').references(() => users.id),
    revokedAt: integer('revoked_at', { mode: 'timestamp_ms' }),
    revokedByUserId: text('revoked_by_user_id').references(() => users.id),
  },
  (table) => [
    index('invitations_email_idx').on(table.email),
    check('invitations_email_normalized', sql`${table.email} = lower(trim(${table.email}))`),
    check('invitations_token_hash_format', sql`length(${table.tokenHash}) = 64`),
    check('invitations_expiry_after_creation', sql`${table.expiresAt} > ${table.createdAt}`),
    check('invitations_single_outcome', sql`${table.acceptedAt} is null or ${table.revokedAt} is null`),
    check(
      'invitations_accepted_user_consistent',
      sql`(${table.acceptedAt} is null) = (${table.acceptedUserId} is null)`,
    ),
  ],
);

/**
 * Workspaces: the collaboration and security boundary. Never hard-deleted by the application
 * (historical Runs will reference them); foreign keys to it do not cascade.
 */
export const workspaces = sqliteTable(
  'workspaces',
  {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    createdByUserId: text('created_by_user_id')
      .notNull()
      .references(() => users.id),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
    /** The image quota of 14.3 (D11a). **Not read since 16.4** — superseded by the combined storage below; the column is kept, not dropped. */
    imageQuotaBytes: integer('image_quota_bytes').notNull().default(100_000_000),
    /**
     * The storage **ceiling** in bytes (16.1 / 16.4, P1), set by the instance admin: a usage limit for
     * everything the Workspace stores (instruction images, Documents, Trash) — nothing is reserved.
     */
    storageQuotaBytes: integer('storage_quota_bytes').notNull().default(5_000_000_000),
    /** The Workspace admin's own lower limit (16.4); NULL = none, the ceiling applies; never above the ceiling (trigger in migration 0030). */
    storageLimitBytes: integer('storage_limit_bytes'),
    /** Compare-and-set version of Workspace tool settings, independent of content revisions. */
    toolsRevision: integer('tools_revision').notNull().default(0),
  },
  (table) => [
    check('workspaces_id_uuid', sql`length(${table.id}) = 36`),
    check('workspaces_name_present', sql`length(trim(${table.name})) > 0`),
  ],
);

/**
 * Instruction images (14.3): the metadata of one processed JPEG in a Workspace. The bytes live in the
 * media store (a file named by `sha256`, shared by identical content across Workspaces). Rows are
 * immutable; the same content in the same Workspace is one row (charged once). Steps and Run snapshots
 * reference rows (foreign keys), so a referenced image can never be deleted; unreferenced ones are
 * removed by housekeeping after a grace period.
 */
export const stepImages = sqliteTable(
  'step_images',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    sha256: text('sha256').notNull(),
    bytes: integer('bytes').notNull(),
    width: integer('width').notNull(),
    height: integer('height').notNull(),
    createdByUserId: text('created_by_user_id')
      .notNull()
      .references(() => users.id),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [
    uniqueIndex('step_images_content_unique').on(table.workspaceId, table.sha256),
    index('step_images_sha_idx').on(table.sha256),
    check('step_images_id_uuid', sql`length(${table.id}) = 36`),
    check('step_images_sha_format', sql`length(${table.sha256}) = 64 and ${table.sha256} not glob '*[^0-9a-f]*'`),
    check('step_images_bytes_bounded', sql`${table.bytes} between 1 and 500000`),
    check('step_images_size_bounded', sql`${table.width} between 1 and 1600 and ${table.height} between 1 and 1600`),
  ],
);

/**
 * Memberships: one role per User and Workspace. Removal deletes the row (recorded as a
 * MEMBERSHIP_REMOVED security event); every authorization reads this table, so it takes effect
 * on the next request.
 */
export const memberships = sqliteTable(
  'memberships',
  {
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    userId: text('user_id')
      .notNull()
      .references(() => users.id),
    role: text('role', { enum: WORKSPACE_ROLES }).notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.workspaceId, table.userId] }),
    index('memberships_user_id_idx').on(table.userId),
    check(
      'memberships_role_valid',
      sql.raw(`role in (${WORKSPACE_ROLES.map((role) => `'${role}'`).join(', ')})`),
    ),
  ],
);

/**
 * The trusted icon keys (PROCEDURE_ICONS). Every icon column references this table, so a new icon is a
 * migration that inserts a row — no table rebuild. Keys are never removed (history keeps its icons).
 */
export const procedureIcons = sqliteTable(
  'procedure_icons',
  {
    key: text('key').primaryKey(),
  },
  (table) => [check('procedure_icons_key_format', sql`${table.key} glob '[a-z]*' and length(${table.key}) between 1 and 40`)],
);

/**
 * Procedures: editable, reusable definitions. Soft-deleted only (`deleted_at`); rows are never
 * removed by the application, and future Run snapshots must not depend on them.
 */
export const procedures = sqliteTable(
  'procedures',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    title: text('title').notNull(),
    /** Plain text; rendered as text, never as HTML. */
    description: text('description').notNull().default(''),
    /** Trusted icon key (PROCEDURE_ICONS, table `procedure_icons`), never a URL or markup. */
    icon: text('icon', { enum: PROCEDURE_ICONS })
      .notNull()
      .references(() => procedureIcons.key),
    tags: text('tags', { mode: 'json' }).$type<string[]>().notNull().default(sql`'[]'`),
    revision: integer('revision').notNull().default(1),
    createdByUserId: text('created_by_user_id')
      .notNull()
      .references(() => users.id),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
    deletedAt: integer('deleted_at', { mode: 'timestamp_ms' }),
    deletedByUserId: text('deleted_by_user_id').references(() => users.id),
  },
  (table) => [
    index('procedures_workspace_idx').on(table.workspaceId, table.deletedAt),
    check('procedures_id_uuid', sql`length(${table.id}) = 36`),
    check('procedures_title_present', sql`length(trim(${table.title})) > 0 and length(${table.title}) <= 120`),
    check('procedures_description_bounded', sql`length(${table.description}) <= 4000`),
    check('procedures_tags_array', sql`json_valid(${table.tags}) and json_type(${table.tags}) = 'array' and json_array_length(${table.tags}) <= 10`),
    check('procedures_revision_positive', sql`${table.revision} >= 1`),
    check('procedures_deletion_consistent', sql`(${table.deletedAt} is null) = (${table.deletedByUserId} is null)`),
  ],
);

const oneOf = (column: string, values: readonly string[]) =>
  sql.raw(`${column} in (${values.map((value) => `'${value}'`).join(', ')})`);

/**
 * Ordered Sections of a Procedure. Rewritten as a whole on every structure save (ids are kept);
 * Run snapshots (Step 5.1) copy what they need and must not reference these rows.
 */
export const procedureSections = sqliteTable(
  'procedure_sections',
  {
    id: text('id').primaryKey(),
    procedureId: text('procedure_id')
      .notNull()
      .references(() => procedures.id),
    position: integer('position').notNull(),
    title: text('title').notNull(),
    description: text('description').notNull().default(''),
  },
  (table) => [
    uniqueIndex('procedure_sections_position_unique').on(table.procedureId, table.position),
    // Target of the composite foreign key from procedure_steps.
    uniqueIndex('procedure_sections_id_procedure_unique').on(table.id, table.procedureId),
    check('procedure_sections_id_uuid', sql`length(${table.id}) = 36`),
    check('procedure_sections_position_bounded', sql`${table.position} >= 0 and ${table.position} < 50`),
    check('procedure_sections_title_present', sql`length(trim(${table.title})) > 0 and length(${table.title}) <= 120`),
    check('procedure_sections_description_bounded', sql`length(${table.description}) <= 4000`),
  ],
);

/** Ordered CHECK Steps. The composite foreign key keeps each Step inside its own Procedure's Sections. */
export const procedureSteps = sqliteTable(
  'procedure_steps',
  {
    id: text('id').primaryKey(),
    procedureId: text('procedure_id')
      .notNull()
      .references(() => procedures.id),
    sectionId: text('section_id').notNull(),
    position: integer('position').notNull(),
    kind: text('kind', { enum: STEP_KINDS }).notNull().default('CHECK'),
    title: text('title').notNull(),
    description: text('description').notNull().default(''),
    icon: text('icon', { enum: PROCEDURE_ICONS }).references(() => procedureIcons.key),
    required: integer('required', { mode: 'boolean' }).notNull(),
    critical: integer('critical', { mode: 'boolean' }).notNull(),
    skipReasonPolicy: text('skip_reason_policy', { enum: REASON_POLICIES }).notNull(),
    notApplicableReasonPolicy: text('not_applicable_reason_policy', { enum: REASON_POLICIES }).notNull(),
    /** Optional instruction image and its caption (14.3); both or neither (trigger in migration 0025). */
    imageId: text('image_id').references(() => stepImages.id),
    imageCaption: text('image_caption'),
  },
  (table) => [
    foreignKey({
      name: 'procedure_steps_section_same_procedure',
      columns: [table.sectionId, table.procedureId],
      foreignColumns: [procedureSections.id, procedureSections.procedureId],
    }),
    uniqueIndex('procedure_steps_position_unique').on(table.sectionId, table.position),
    index('procedure_steps_procedure_idx').on(table.procedureId),
    index('procedure_steps_image_idx').on(table.imageId),
    check('procedure_steps_id_uuid', sql`length(${table.id}) = 36`),
    check('procedure_steps_position_bounded', sql`${table.position} >= 0 and ${table.position} < 200`),
    check('procedure_steps_kind_valid', oneOf('kind', STEP_KINDS)),
    check('procedure_steps_title_present', sql`length(trim(${table.title})) > 0 and length(${table.title}) <= 200`),
    check('procedure_steps_description_bounded', sql`length(${table.description}) <= 4000`),
    check('procedure_steps_skip_policy_valid', oneOf('skip_reason_policy', REASON_POLICIES)),
    check('procedure_steps_na_policy_valid', oneOf('not_applicable_reason_policy', REASON_POLICIES)),
  ],
);

/**
 * Runs: historical executions. The definition columns are a snapshot taken when the Run started and
 * are immutable (triggers in migration 0011); only `state` and `revision` change later. Runs are never
 * deleted. `procedure_id` points at the source Procedure (never cascades; blocks a hard delete).
 */
export const runs = sqliteTable(
  'runs',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    procedureId: text('procedure_id')
      .notNull()
      .references(() => procedures.id),
    procedureRevision: integer('procedure_revision').notNull(),
    title: text('title').notNull(),
    description: text('description').notNull(),
    icon: text('icon', { enum: PROCEDURE_ICONS })
      .notNull()
      .references(() => procedureIcons.key),
    tags: text('tags', { mode: 'json' }).$type<string[]>().notNull(),
    state: text('state', { enum: RUN_STATES }).notNull().default('ACTIVE'),
    /** Concurrency token for later state changes (5.2 / 6.1). */
    revision: integer('revision').notNull().default(1),
    startedByUserId: text('started_by_user_id')
      .notNull()
      .references(() => users.id),
    startedByDisplayName: text('started_by_display_name').notNull(),
    startedAt: integer('started_at', { mode: 'timestamp_ms' }).notNull(),
    /** Set when the Run is completed or aborted (all NULL while ACTIVE). Added by migration 0013. */
    endedAt: integer('ended_at', { mode: 'timestamp_ms' }),
    endedByUserId: text('ended_by_user_id').references(() => users.id),
    endedByDisplayName: text('ended_by_display_name'),
    /** Optional abort reason. */
    endReason: text('end_reason'),
  },
  (table) => [
    index('runs_workspace_state_idx').on(table.workspaceId, table.state, table.startedAt),
    index('runs_procedure_idx').on(table.procedureId),
    // Recent Procedures of a person (13.13).
    index('runs_starter_idx').on(table.workspaceId, table.startedByUserId, table.startedAt),
    check('runs_id_uuid', sql`length(${table.id}) = 36`),
    check('runs_state_valid', oneOf('state', RUN_STATES)),
    check('runs_title_present', sql`length(trim(${table.title})) > 0 and length(${table.title}) <= 120`),
    check('runs_tags_array', sql`json_valid(${table.tags}) and json_type(${table.tags}) = 'array'`),
    check('runs_revisions_positive', sql`${table.procedureRevision} >= 1 and ${table.revision} >= 1`),
    check(
      'runs_end_consistent',
      sql`(${table.endedAt} is null) = (${table.state} = 'ACTIVE') and (${table.endedAt} is null) = (${table.endedByUserId} is null) and (${table.endedAt} is null) = (${table.endedByDisplayName} is null)`,
    ),
    check(
      'runs_end_reason_only_when_aborted',
      sql`${table.endReason} is null or (${table.state} = 'ABORTED' and length(trim(${table.endReason})) > 0 and length(${table.endReason}) <= 500)`,
    ),
  ],
);

/** Snapshot of a Section at Run start. Immutable. */
export const runSections = sqliteTable(
  'run_sections',
  {
    id: text('id').primaryKey(),
    runId: text('run_id')
      .notNull()
      .references(() => runs.id),
    position: integer('position').notNull(),
    /** The Procedure Section it was copied from (informational; no FK — those rows are rewritten on save). */
    sourceSectionId: text('source_section_id').notNull(),
    title: text('title').notNull(),
    description: text('description').notNull(),
  },
  (table) => [
    uniqueIndex('run_sections_position_unique').on(table.runId, table.position),
    uniqueIndex('run_sections_id_run_unique').on(table.id, table.runId),
    check('run_sections_id_uuid', sql`length(${table.id}) = 36`),
  ],
);

/** Snapshot of a Step at Run start. Definition columns are immutable; `state` is the execution state. */
export const runSteps = sqliteTable(
  'run_steps',
  {
    id: text('id').primaryKey(),
    runId: text('run_id')
      .notNull()
      .references(() => runs.id),
    runSectionId: text('run_section_id').notNull(),
    position: integer('position').notNull(),
    sourceStepId: text('source_step_id').notNull(),
    kind: text('kind', { enum: STEP_KINDS }).notNull(),
    title: text('title').notNull(),
    description: text('description').notNull(),
    icon: text('icon', { enum: PROCEDURE_ICONS }).references(() => procedureIcons.key),
    required: integer('required', { mode: 'boolean' }).notNull(),
    critical: integer('critical', { mode: 'boolean' }).notNull(),
    skipReasonPolicy: text('skip_reason_policy', { enum: REASON_POLICIES }).notNull(),
    notApplicableReasonPolicy: text('not_applicable_reason_policy', { enum: REASON_POLICIES }).notNull(),
    state: text('state', { enum: STEP_STATES }).notNull().default('PENDING'),
    // Who set the current state, when and why (all NULL until the first change). Execution state:
    // writable, but only while the Run is ACTIVE (trigger in migration 0013).
    stateReason: text('state_reason'),
    stateChangedByUserId: text('state_changed_by_user_id').references(() => users.id),
    stateChangedByDisplayName: text('state_changed_by_display_name'),
    stateChangedAt: integer('state_changed_at', { mode: 'timestamp_ms' }),
    /**
     * Device clock of a change made offline and sent later (Step 8.5). Reported by the client, so
     * never authoritative: `state_changed_at` stays the server time. Only stored when plausible.
     */
    stateChangedDeviceAt: integer('state_changed_device_at', { mode: 'timestamp_ms' }),
    /** The Step's instruction image when the Run started (14.3): snapshot, immutable (triggers in migration 0025). */
    imageId: text('image_id').references(() => stepImages.id),
    imageCaption: text('image_caption'),
  },
  (table) => [
    foreignKey({
      name: 'run_steps_section_same_run',
      columns: [table.runSectionId, table.runId],
      foreignColumns: [runSections.id, runSections.runId],
    }),
    uniqueIndex('run_steps_position_unique').on(table.runSectionId, table.position),
    index('run_steps_run_idx').on(table.runId),
    index('run_steps_image_idx').on(table.imageId),
    check('run_steps_id_uuid', sql`length(${table.id}) = 36`),
    check('run_steps_kind_valid', oneOf('kind', STEP_KINDS)),
    check('run_steps_skip_policy_valid', oneOf('skip_reason_policy', REASON_POLICIES)),
    check('run_steps_na_policy_valid', oneOf('not_applicable_reason_policy', REASON_POLICIES)),
    check('run_steps_state_valid', oneOf('state', STEP_STATES)),
    check(
      'run_steps_state_change_complete',
      sql`(${table.stateChangedByUserId} is null) = (${table.stateChangedByDisplayName} is null) and (${table.stateChangedByUserId} is null) = (${table.stateChangedAt} is null)`,
    ),
    check('run_steps_device_time_with_change', sql`${table.stateChangedDeviceAt} is null or ${table.stateChangedAt} is not null`),
    check(
      'run_steps_reason_only_when_skipped_or_na',
      sql`${table.stateReason} is null or (${table.state} in ('SKIPPED', 'NOT_APPLICABLE') and length(trim(${table.stateReason})) > 0 and length(${table.stateReason}) <= 500)`,
    ),
  ],
);

/**
 * Append-only history of Workspace content (UPDATE/DELETE blocked by triggers in migration 0008).
 * Procedures now; Run and Step events join with Step 5.5. Metadata is JSON and never holds secrets.
 */
export const auditEvents = sqliteTable(
  'audit_events',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    occurredAt: integer('occurred_at', { mode: 'timestamp_ms' }).notNull(),
    type: text('type').notNull(),
    actorUserId: text('actor_user_id')
      .notNull()
      .references(() => users.id),
    /** Display-name snapshot at the time of the event. */
    actorDisplayName: text('actor_display_name').notNull(),
    subjectType: text('subject_type').notNull(),
    subjectId: text('subject_id').notNull(),
    /** Set for every Run event (AGENTS.md: Run events identify the Run UUID). */
    runId: text('run_id').references(() => runs.id),
    metadata: text('metadata', { mode: 'json' }).$type<Record<string, string | number | boolean | string[]>>(),
    /** Client-chosen id of an offline change (Step 8.5): the same change sent twice is applied once. */
    clientChangeId: text('client_change_id'),
  },
  (table) => [
    index('audit_events_run_idx').on(table.runId),
    uniqueIndex('audit_events_client_change_unique')
      .on(table.actorUserId, table.clientChangeId)
      .where(sql`${table.clientChangeId} is not null`),
    index('audit_events_subject_idx').on(table.workspaceId, table.subjectType, table.subjectId),
    index('audit_events_occurred_at_idx').on(table.workspaceId, table.occurredAt),
  ],
);

/**
 * Knot links (Step 7.1): an opaque token pointing at one Procedure or Run of the Workspace. Only the
 * token's SHA-256 is stored. Rows are never deleted; after creation only the revocation columns can
 * be set, exactly once (triggers in migration 0014).
 */
export const knots = sqliteTable(
  'knots',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    tokenHash: text('token_hash').notNull().unique(),
    label: text('label').notNull(),
    targetType: text('target_type', { enum: KNOT_TARGET_TYPES }).notNull(),
    procedureId: text('procedure_id').references(() => procedures.id),
    runId: text('run_id').references(() => runs.id),
    createdByUserId: text('created_by_user_id')
      .notNull()
      .references(() => users.id),
    createdByDisplayName: text('created_by_display_name').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    /** NULL = does not expire. */
    expiresAt: integer('expires_at', { mode: 'timestamp_ms' }),
    revokedAt: integer('revoked_at', { mode: 'timestamp_ms' }),
    revokedByUserId: text('revoked_by_user_id').references(() => users.id),
    revokedByDisplayName: text('revoked_by_display_name'),
  },
  (table) => [
    index('knots_workspace_idx').on(table.workspaceId, table.createdAt),
    check('knots_id_uuid', sql`length(${table.id}) = 36`),
    check('knots_token_hash_format', sql`length(${table.tokenHash}) = 64`),
    check('knots_label_present', sql`length(trim(${table.label})) > 0 and length(${table.label}) <= 80`),
    check('knots_target_type_valid', oneOf('target_type', KNOT_TARGET_TYPES)),
    check(
      'knots_target_consistent',
      sql`(${table.targetType} = 'PROCEDURE' and ${table.procedureId} is not null and ${table.runId} is null) or (${table.targetType} = 'RUN' and ${table.runId} is not null and ${table.procedureId} is null)`,
    ),
    check('knots_expiry_after_creation', sql`${table.expiresAt} is null or ${table.expiresAt} > ${table.createdAt}`),
    check(
      'knots_revocation_consistent',
      sql`(${table.revokedAt} is null) = (${table.revokedByUserId} is null) and (${table.revokedAt} is null) = (${table.revokedByDisplayName} is null)`,
    ),
  ],
);

/**
 * Append-only security event log (UPDATE/DELETE blocked by triggers in migration 0002).
 * Metadata is JSON and must never contain secrets.
 */
export const securityEvents = sqliteTable(
  'security_events',
  {
    id: text('id').primaryKey(),
    occurredAt: integer('occurred_at', { mode: 'timestamp_ms' }).notNull(),
    type: text('type').notNull(),
    actorUserId: text('actor_user_id').references(() => users.id),
    /** Display-name snapshot for users, or the system channel label (e.g. `cli:admin-bootstrap`). */
    actorLabel: text('actor_label').notNull(),
    subjectType: text('subject_type').notNull(),
    subjectId: text('subject_id').notNull(),
    metadata: text('metadata', { mode: 'json' }).$type<Record<string, string | number | boolean>>(),
  },
  (table) => [
    index('security_events_subject_idx').on(table.subjectType, table.subjectId),
    index('security_events_occurred_at_idx').on(table.occurredAt),
  ],
);

/**
 * Persistent fixed-window counters for the security-sensitive rate limits (sign-in, MFA, recovery,
 * invitations, account security), so a restart does not reset them (Step 2.9). `key_hash` is the
 * SHA-256 of route + client/account key: no email address or IP is stored in clear. Expired rows are
 * removed by housekeeping (Step 2.8).
 */
export const rateLimits = sqliteTable(
  'rate_limits',
  {
    keyHash: text('key_hash').primaryKey(),
    hits: integer('hits').notNull(),
    windowStart: integer('window_start', { mode: 'timestamp_ms' }).notNull(),
    windowMs: integer('window_ms').notNull(),
  },
  (table) => [
    index('rate_limits_window_idx').on(table.windowStart),
    check('rate_limits_key_hash_format', sql`length(${table.keyHash}) = 64`),
    check('rate_limits_counts_positive', sql`${table.hits} > 0 and ${table.windowMs} > 0`),
  ],
);

/** Presentation preferences of an account (Step 8.7). No row = defaults. */
export const userPreferences = sqliteTable(
  'user_preferences',
  {
    userId: text('user_id')
      .primaryKey()
      .references(() => users.id),
    theme: text('theme', { enum: THEME_PREFERENCES }).notNull(),
    criticalConfirm: text('critical_confirm', { enum: CRITICAL_CONFIRM_MODES }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  },
  () => [
    check('user_preferences_theme_valid', sql.raw(`theme in (${THEME_PREFERENCES.map((value) => `'${value}'`).join(', ')})`)),
    check(
      'user_preferences_critical_confirm_valid',
      sql.raw(`critical_confirm in (${CRITICAL_CONFIRM_MODES.map((value) => `'${value}'`).join(', ')})`),
    ),
  ],
);

/**
 * Settings of this server (Step 8.10), changed by server admins only. Exactly one row (id 1); no row
 * yet = defaults.
 */
export const instanceSettings = sqliteTable(
  'instance_settings',
  {
    id: integer('id').primaryKey(),
    /** Hide the page footer (it stays in the HTML, with the `hidden` attribute). */
    footerHidden: integer('footer_hidden', { mode: 'boolean' }).notNull().default(false),
    /** How many recently started Procedures Home shows per user (13.13); 0 hides the section. */
    recentProceduresLimit: integer('recent_procedures_limit').notNull().default(5),
    /** Largest accepted document file in bytes (16.1, H8); bounded by a trigger in migration 0027. */
    documentMaxFileBytes: integer('document_max_file_bytes').notNull().default(50_000_000),
    /** Accepted document formats, comma-separated in canonical order — a subset of PDF,JPEG,PNG,HEIC. */
    documentFormats: text('document_formats').notNull().default('PDF,JPEG,PNG,HEIC'),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
    updatedByUserId: text('updated_by_user_id')
      .notNull()
      .references(() => users.id),
  },
  (table) => [
    check('instance_settings_single_row', sql`${table.id} = 1`),
    check('instance_settings_recent_limit_bounded', sql`${table.recentProceduresLimit} between 0 and 20`),
  ],
);

/**
 * Schedules (14.1): a series of a standalone Reminder or of a Procedure. Not a Run — nothing is
 * executed or recorded as done when a date arrives. Dates are wall-clock values in `time_zone`.
 * Rows are never deleted (ending keeps the history); the Procedure is referenced without cascade (a
 * deleted Procedure leaves its Occurrences visible as unavailable). Existing one-time scheduled
 * Procedures (13.4) were migrated with their ids in migration 0024.
 */
export const schedules = sqliteTable(
  'schedules',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    kind: text('kind', { enum: SCHEDULE_KINDS }).notNull(),
    /** PROCEDURE only. */
    procedureId: text('procedure_id').references(() => procedures.id),
    /** REMINDER only (plain text). */
    title: text('title'),
    description: text('description').notNull().default(''),
    recurrenceKind: text('recurrence_kind', { enum: RECURRENCE_KINDS }).notNull(),
    recurrenceUnit: text('recurrence_unit', { enum: RECURRENCE_UNITS }),
    recurrenceInterval: integer('recurrence_interval'),
    /** FIXED weekly: ISO weekdays 1–7, sorted. */
    recurrenceWeekdays: text('recurrence_weekdays', { mode: 'json' }).$type<number[]>(),
    recurrenceLastDay: integer('recurrence_last_day', { mode: 'boolean' }).notNull().default(false),
    /** First due date; fixed recurrence is always computed from it (no drift). */
    anchorDate: text('anchor_date').notNull(),
    time: text('time'),
    timeZone: text('time_zone').notNull(),
    /** Normalized offsets `[{unit, amount}]`, at most 5. */
    reminders: text('reminders', { mode: 'json' }).$type<{ unit: 'DAYS' | 'WEEKS' | 'MONTHS' | 'HOURS'; amount: number }[]>().notNull(),
    /** Optional responsible member; grants nothing. */
    assigneeUserId: text('assignee_user_id').references(() => users.id),
    state: text('state', { enum: SCHEDULE_STATES }).notNull().default('ACTIVE'),
    pausedAt: integer('paused_at', { mode: 'timestamp_ms' }),
    endedAt: integer('ended_at', { mode: 'timestamp_ms' }),
    endedByUserId: text('ended_by_user_id').references(() => users.id),
    endedByDisplayName: text('ended_by_display_name'),
    revision: integer('revision').notNull().default(1),
    createdByUserId: text('created_by_user_id')
      .notNull()
      .references(() => users.id),
    createdByDisplayName: text('created_by_display_name').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [
    index('schedules_workspace_idx').on(table.workspaceId, table.state),
    index('schedules_procedure_idx').on(table.procedureId),
    check('schedules_id_uuid', sql`length(${table.id}) = 36`),
    check('schedules_kind_valid', oneOf('kind', SCHEDULE_KINDS)),
    check('schedules_kind_consistent', sql`(${table.kind} = 'PROCEDURE') = (${table.procedureId} is not null) and (${table.kind} = 'REMINDER') = (${table.title} is not null)`),
    check('schedules_title_bounded', sql`${table.title} is null or length(${table.title}) between 1 and 120`),
    check('schedules_description_bounded', sql`length(${table.description}) <= 4000`),
    check('schedules_recurrence_kind_valid', oneOf('recurrence_kind', RECURRENCE_KINDS)),
    check(
      'schedules_recurrence_consistent',
      sql`(${table.recurrenceKind} = 'ONCE') = (${table.recurrenceUnit} is null) and (${table.recurrenceUnit} is null) = (${table.recurrenceInterval} is null) and (${table.recurrenceUnit} is null or ${table.recurrenceUnit} in ('DAY', 'WEEK', 'MONTH', 'YEAR')) and (${table.recurrenceInterval} is null or ${table.recurrenceInterval} between 1 and 99)`,
    ),
    check(
      'schedules_weekdays_valid',
      sql`${table.recurrenceWeekdays} is null or (${table.recurrenceKind} = 'FIXED' and ${table.recurrenceUnit} = 'WEEK' and json_valid(${table.recurrenceWeekdays}) and json_type(${table.recurrenceWeekdays}) = 'array' and json_array_length(${table.recurrenceWeekdays}) between 1 and 7)`,
    ),
    check('schedules_last_day_valid', sql`${table.recurrenceLastDay} = 0 or (${table.recurrenceKind} = 'FIXED' and ${table.recurrenceUnit} = 'MONTH')`),
    check('schedules_anchor_format', sql`${table.anchorDate} glob '[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]'`),
    check('schedules_time_format', sql`${table.time} is null or ${table.time} glob '[0-2][0-9]:[0-5][0-9]'`),
    check('schedules_time_zone_bounded', sql`length(${table.timeZone}) between 1 and 64`),
    check('schedules_reminders_array', sql`json_valid(${table.reminders}) and json_type(${table.reminders}) = 'array' and json_array_length(${table.reminders}) <= 5`),
    check('schedules_state_valid', oneOf('state', SCHEDULE_STATES)),
    check('schedules_paused_consistent', sql`(${table.state} = 'PAUSED') = (${table.pausedAt} is not null)`),
    check(
      'schedules_ended_consistent',
      sql`(${table.state} = 'ENDED') = (${table.endedAt} is not null) and (${table.endedAt} is null) = (${table.endedByUserId} is null) and (${table.endedAt} is null) = (${table.endedByDisplayName} is null)`,
    ),
    check('schedules_revision_positive', sql`${table.revision} >= 1`),
  ],
);

/**
 * One dated instance of a Schedule (14.1) with its own state and history. Unique per (Schedule, due
 * date) among non-cancelled rows — also the idempotency key of the generator. OPEN/IN_PROGRESS are
 * open; COMPLETED, SKIPPED and CANCELLED record who and when. Never deleted.
 */
export const occurrences = sqliteTable(
  'occurrences',
  {
    id: text('id').primaryKey(),
    scheduleId: text('schedule_id')
      .notNull()
      .references(() => schedules.id),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    dueDate: text('due_date').notNull(),
    time: text('time'),
    state: text('state', { enum: OCCURRENCE_STATES }).notNull().default('OPEN'),
    /** Overrides the Schedule's Assignee for this Occurrence; grants nothing. */
    assigneeUserId: text('assignee_user_id').references(() => users.id),
    closedAt: integer('closed_at', { mode: 'timestamp_ms' }),
    closedByUserId: text('closed_by_user_id').references(() => users.id),
    closedByDisplayName: text('closed_by_display_name'),
    skipReason: text('skip_reason'),
    revision: integer('revision').notNull().default(1),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [
    uniqueIndex('occurrences_due_unique')
      .on(table.scheduleId, table.dueDate)
      .where(sql`${table.state} <> 'CANCELLED'`),
    index('occurrences_workspace_idx').on(table.workspaceId, table.state, table.dueDate),
    index('occurrences_schedule_idx').on(table.scheduleId, table.dueDate),
    check('occurrences_id_uuid', sql`length(${table.id}) = 36`),
    check('occurrences_due_format', sql`${table.dueDate} glob '[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]'`),
    check('occurrences_time_format', sql`${table.time} is null or ${table.time} glob '[0-2][0-9]:[0-5][0-9]'`),
    check('occurrences_state_valid', oneOf('state', OCCURRENCE_STATES)),
    check(
      'occurrences_closed_consistent',
      sql`(${table.state} in ('COMPLETED', 'SKIPPED', 'CANCELLED')) = (${table.closedAt} is not null) and (${table.closedAt} is null) = (${table.closedByUserId} is null) and (${table.closedAt} is null) = (${table.closedByDisplayName} is null)`,
    ),
    check('occurrences_skip_reason_valid', sql`${table.skipReason} is null or (${table.state} = 'SKIPPED' and length(${table.skipReason}) between 1 and 500)`),
    check('occurrences_revision_positive', sql`${table.revision} >= 1`),
  ],
);

/**
 * Links between Occurrences and Runs (14.1, D7): started from the Occurrence or deliberately linked.
 * At most one current link per Occurrence and per Run; an aborted or unlinked Run stays in the history
 * (`ended_at`). Never deleted.
 */
export const occurrenceRuns = sqliteTable(
  'occurrence_runs',
  {
    id: text('id').primaryKey(),
    occurrenceId: text('occurrence_id')
      .notNull()
      .references(() => occurrences.id),
    runId: text('run_id')
      .notNull()
      .references(() => runs.id),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    how: text('how', { enum: ['STARTED', 'LINKED'] }).notNull(),
    linkedAt: integer('linked_at', { mode: 'timestamp_ms' }).notNull(),
    linkedByUserId: text('linked_by_user_id')
      .notNull()
      .references(() => users.id),
    linkedByDisplayName: text('linked_by_display_name').notNull(),
    endedAt: integer('ended_at', { mode: 'timestamp_ms' }),
    endReason: text('end_reason', { enum: ['ABORTED', 'UNLINKED'] }),
  },
  (table) => [
    uniqueIndex('occurrence_runs_current_run')
      .on(table.runId)
      .where(sql`${table.endedAt} is null`),
    uniqueIndex('occurrence_runs_current_occurrence')
      .on(table.occurrenceId)
      .where(sql`${table.endedAt} is null`),
    index('occurrence_runs_occurrence_idx').on(table.occurrenceId),
    check('occurrence_runs_id_uuid', sql`length(${table.id}) = 36`),
    check('occurrence_runs_how_valid', sql`${table.how} in ('STARTED', 'LINKED')`),
    check('occurrence_runs_end_consistent', sql`(${table.endedAt} is null) = (${table.endReason} is null) and (${table.endReason} is null or ${table.endReason} in ('ABORTED', 'UNLINKED'))`),
  ],
);

/**
 * One row per reminder instant of an Occurrence and recipient (13.5, 14.1) — the logical notification
 * key is (Occurrence, recipient, offset, instant). Reminders already due when they are computed are
 * not created. When the Occurrence is moved, reassigned, closed or its Schedule paused, unprocessed
 * rows are cancelled (kept; deliveries may reference them). `superseded_at`: a missed reminder
 * covered by a later catch-up (D5) — processed without being sent.
 */
export const scheduledReminders = sqliteTable(
  'scheduled_reminders',
  {
    id: text('id').primaryKey(),
    occurrenceId: text('occurrence_id')
      .notNull()
      .references(() => occurrences.id),
    /** `DAYS:7`, `WEEKS:1`, `MONTHS:1`, `HOURS:3`, … */
    reminderKey: text('reminder_key').notNull(),
    remindAt: integer('remind_at', { mode: 'timestamp_ms' }).notNull(),
    recipientUserId: text('recipient_user_id')
      .notNull()
      .references(() => users.id),
    /** Every channel reached a final state (sent, failed or skipped), or it was superseded. */
    processedAt: integer('processed_at', { mode: 'timestamp_ms' }),
    /** A channel waits for a retry: not looked at again before this time. */
    nextAttemptAt: integer('next_attempt_at', { mode: 'timestamp_ms' }),
    cancelledAt: integer('cancelled_at', { mode: 'timestamp_ms' }),
    supersededAt: integer('superseded_at', { mode: 'timestamp_ms' }),
  },
  (table) => [
    uniqueIndex('scheduled_reminders_instant_unique').on(table.occurrenceId, table.recipientUserId, table.reminderKey, table.remindAt),
    index('scheduled_reminders_due_idx').on(table.processedAt, table.cancelledAt, table.remindAt),
    check('scheduled_reminders_id_uuid', sql`length(${table.id}) = 36`),
    check('scheduled_reminders_key_format', sql`${table.reminderKey} glob '[A-Z]*:[0-9]*' and length(${table.reminderKey}) <= 16`),
    check('scheduled_reminders_superseded_processed', sql`${table.supersededAt} is null or ${table.processedAt} is not null`),
  ],
);

export const NOTIFICATION_CHANNELS = ['EMAIL', 'TELEGRAM'] as const;
export const DELIVERY_STATUSES = ['SENDING', 'RETRY', 'SENT', 'FAILED', 'SKIPPED', 'GROUPED'] as const;
export const SUMMARY_STATUSES = ['SENDING', 'RETRY', 'SENT', 'FAILED', 'SKIPPED'] as const;

/**
 * One catch-up summary (D5): the missed reminders of one recipient through one channel, sent as a
 * single bounded message. Claimed, leased and retried like a delivery; its member deliveries
 * (status GROUPED) take its final outcome.
 */
export const notificationSummaries = sqliteTable(
  'notification_summaries',
  {
    id: text('id').primaryKey(),
    recipientUserId: text('recipient_user_id')
      .notNull()
      .references(() => users.id),
    channel: text('channel', { enum: NOTIFICATION_CHANNELS }).notNull(),
    status: text('status', { enum: SUMMARY_STATUSES }).notNull(),
    attempts: integer('attempts').notNull(),
    nextAttemptAt: integer('next_attempt_at', { mode: 'timestamp_ms' }),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
    sentAt: integer('sent_at', { mode: 'timestamp_ms' }),
    errorCode: text('error_code'),
  },
  (table) => [
    index('notification_summaries_retry_idx').on(table.status, table.nextAttemptAt),
    check('notification_summaries_id_uuid', sql`length(${table.id}) = 36`),
    check('notification_summaries_channel_valid', oneOf('channel', NOTIFICATION_CHANNELS)),
    check('notification_summaries_status_valid', oneOf('status', SUMMARY_STATUSES)),
    check('notification_summaries_attempts_bounded', sql`${table.attempts} between 0 and 10`),
    check('notification_summaries_sent_consistent', sql`(${table.status} = 'SENT') = (${table.sentAt} is not null)`),
    check('notification_summaries_error_code_bounded', sql`${table.errorCode} is null or length(${table.errorCode}) <= 40`),
  ],
);

/**
 * Delivery of one reminder through one channel (13.5). The unique (reminder, channel) row is claimed
 * *before* sending, so restarts and overlapping workers never send a reminder twice through a channel;
 * attempts are bounded. GROUPED: part of a catch-up summary (`summary_id`), finished with it.
 * A failed delivery never touches Procedures, Runs or their history.
 */
export const reminderDeliveries = sqliteTable(
  'reminder_deliveries',
  {
    id: text('id').primaryKey(),
    reminderId: text('reminder_id')
      .notNull()
      .references(() => scheduledReminders.id),
    channel: text('channel', { enum: NOTIFICATION_CHANNELS }).notNull(),
    status: text('status', { enum: DELIVERY_STATUSES }).notNull(),
    attempts: integer('attempts').notNull(),
    /** RETRY: not before; SENDING: the claim expires (then treated as interrupted). */
    nextAttemptAt: integer('next_attempt_at', { mode: 'timestamp_ms' }),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
    sentAt: integer('sent_at', { mode: 'timestamp_ms' }),
    /** Stable reason code only — never provider responses, addresses or tokens. */
    errorCode: text('error_code'),
    summaryId: text('summary_id').references(() => notificationSummaries.id),
  },
  (table) => [
    uniqueIndex('reminder_deliveries_once_per_channel').on(table.reminderId, table.channel),
    index('reminder_deliveries_retry_idx').on(table.status, table.nextAttemptAt),
    index('reminder_deliveries_summary_idx').on(table.summaryId),
    check('reminder_deliveries_id_uuid', sql`length(${table.id}) = 36`),
    check('reminder_deliveries_channel_valid', oneOf('channel', NOTIFICATION_CHANNELS)),
    check('reminder_deliveries_status_valid', oneOf('status', DELIVERY_STATUSES)),
    check('reminder_deliveries_attempts_bounded', sql`${table.attempts} between 0 and 10`),
    check('reminder_deliveries_sent_consistent', sql`(${table.status} = 'SENT') = (${table.sentAt} is not null)`),
    check('reminder_deliveries_error_code_bounded', sql`${table.errorCode} is null or length(${table.errorCode}) <= 40`),
    check('reminder_deliveries_grouped_summary', sql`${table.status} <> 'GROUPED' or ${table.summaryId} is not null`),
  ],
);

/** Each person's reminder channels and default reminder time (13.8). No row = defaults. */
export const notificationPreferences = sqliteTable(
  'notification_preferences',
  {
    userId: text('user_id')
      .primaryKey()
      .references(() => users.id),
    reminderTime: text('reminder_time').notNull(),
    emailReminders: integer('email_reminders', { mode: 'boolean' }).notNull(),
    telegramReminders: integer('telegram_reminders', { mode: 'boolean' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [check('notification_preferences_reminder_time_format', sql`${table.reminderTime} glob '[0-2][0-9]:[0-5][0-9]'`)],
);

/**
 * Server-wide notification providers (13.7), configured by server admins. `sealed_secret` holds a
 * provider credential (the Telegram bot token) encrypted with DATA_ENCRYPTION_KEY — it is never
 * returned to any client. `public_label` is non-secret (e.g. the bot's @name for pairing links).
 */
export const notificationProviders = sqliteTable(
  'notification_providers',
  {
    provider: text('provider', { enum: NOTIFICATION_CHANNELS }).primaryKey(),
    enabled: integer('enabled', { mode: 'boolean' }).notNull(),
    sealedSecret: text('sealed_secret'),
    publicLabel: text('public_label'),
    /** Telegram: next `getUpdates` offset, so an update is processed once. */
    pollOffset: integer('poll_offset'),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
    updatedByUserId: text('updated_by_user_id').references(() => users.id),
  },
  (table) => [
    check('notification_providers_valid', oneOf('provider', NOTIFICATION_CHANNELS)),
    check('notification_providers_sealed_format', sql`${table.sealedSecret} is null or ${table.sealedSecret} like 'v1.%'`),
    check('notification_providers_label_bounded', sql`${table.publicLabel} is null or length(${table.publicLabel}) <= 64`),
  ],
);

/**
 * Telegram chats connected to accounts (13.7): where reminders go. The chat id is an address, never
 * an authentication credential for VMN.
 */
export const telegramLinks = sqliteTable(
  'telegram_links',
  {
    userId: text('user_id')
      .primaryKey()
      .references(() => users.id),
    chatId: text('chat_id').notNull(),
    /** What Telegram reported for the chat (e.g. `@name` or a first name), sanitized, for display. */
    chatLabel: text('chat_label').notNull(),
    connectedAt: integer('connected_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [
    check('telegram_links_chat_id_format', sql`${table.chatId} glob '[0-9]*' and length(${table.chatId}) between 1 and 20`),
    check('telegram_links_label_bounded', sql`length(${table.chatLabel}) between 1 and 64`),
  ],
);

/**
 * Pairing of a Telegram chat with an account (13.7): a 256-bit one-time token (SHA-256 stored) that
 * the user sends to the bot with /start; the chat is only connected after the signed-in user
 * confirms it in VMN. Short-lived; claimed, completed and cancelled at most once.
 */
export const telegramPairings = sqliteTable(
  'telegram_pairings',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id),
    tokenHash: text('token_hash').notNull().unique(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
    claimedAt: integer('claimed_at', { mode: 'timestamp_ms' }),
    chatId: text('chat_id'),
    chatLabel: text('chat_label'),
    completedAt: integer('completed_at', { mode: 'timestamp_ms' }),
    cancelledAt: integer('cancelled_at', { mode: 'timestamp_ms' }),
  },
  (table) => [
    index('telegram_pairings_user_idx').on(table.userId),
    check('telegram_pairings_id_uuid', sql`length(${table.id}) = 36`),
    check('telegram_pairings_token_hash_format', sql`length(${table.tokenHash}) = 64`),
    check('telegram_pairings_expiry_after_creation', sql`${table.expiresAt} > ${table.createdAt}`),
    check('telegram_pairings_claim_consistent', sql`(${table.claimedAt} is null) = (${table.chatId} is null) and (${table.chatId} is null) = (${table.chatLabel} is null)`),
    check('telegram_pairings_completed_after_claim', sql`${table.completedAt} is null or ${table.claimedAt} is not null`),
    check('telegram_pairings_single_outcome', sql`${table.completedAt} is null or ${table.cancelledAt} is null`),
  ],
);

/** A person's pinned Procedures (13.12): personal, not Workspace history, never audited. */
export const procedurePins = sqliteTable(
  'procedure_pins',
  {
    userId: text('user_id')
      .notNull()
      .references(() => users.id),
    procedureId: text('procedure_id')
      .notNull()
      .references(() => procedures.id),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    pinnedAt: integer('pinned_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [primaryKey({ columns: [table.userId, table.procedureId] }), index('procedure_pins_workspace_idx').on(table.userId, table.workspaceId)],
);

/**
 * Lists (15.3): lightweight shared content of a Workspace — so far grocery lists. Not a Procedure and
 * not a Run: no snapshot, no Step rules. A List is soft-deleted (and can be restored); `revision`
 * increases with every change to the List or its items, so clients notice what they missed.
 */
export const lists = sqliteTable(
  'lists',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    kind: text('kind', { enum: LIST_KINDS }).notNull(),
    title: text('title').notNull(),
    revision: integer('revision').notNull().default(1),
    createdByUserId: text('created_by_user_id')
      .notNull()
      .references(() => users.id),
    createdByDisplayName: text('created_by_display_name').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
    deletedAt: integer('deleted_at', { mode: 'timestamp_ms' }),
    deletedByUserId: text('deleted_by_user_id').references(() => users.id),
    deletedByDisplayName: text('deleted_by_display_name'),
  },
  (table) => [
    index('lists_workspace_idx').on(table.workspaceId, table.deletedAt),
    // Lets list_items reference (list, workspace) together: an item can never sit in another Workspace's List.
    uniqueIndex('lists_id_workspace_unique').on(table.id, table.workspaceId),
    check('lists_id_uuid', sql`length(${table.id}) = 36`),
    check('lists_kind_valid', oneOf('kind', LIST_KINDS)),
    check('lists_title_present', sql`length(trim(${table.title})) > 0 and length(${table.title}) <= 80`),
    check('lists_revision_positive', sql`${table.revision} >= 1`),
    check(
      'lists_deletion_consistent',
      sql`(${table.deletedAt} is null) = (${table.deletedByUserId} is null) and (${table.deletedAt} is null) = (${table.deletedByDisplayName} is null)`,
    ),
  ],
);

/**
 * Items of a List. Checked = purchased, with who and when. Removing an item is a soft delete, so it
 * can be put back (Undo). Who added and who checked are display-name snapshots, like audit history.
 */
export const listItems = sqliteTable(
  'list_items',
  {
    id: text('id').primaryKey(),
    listId: text('list_id').notNull(),
    workspaceId: text('workspace_id').notNull(),
    position: integer('position').notNull(),
    title: text('title').notNull(),
    /** A positive decimal as text, e.g. `1.5`; NULL = none. */
    quantity: text('quantity'),
    unit: text('unit'),
    revision: integer('revision').notNull().default(1),
    createdByUserId: text('created_by_user_id')
      .notNull()
      .references(() => users.id),
    createdByDisplayName: text('created_by_display_name').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    checkedAt: integer('checked_at', { mode: 'timestamp_ms' }),
    checkedByUserId: text('checked_by_user_id').references(() => users.id),
    checkedByDisplayName: text('checked_by_display_name'),
    deletedAt: integer('deleted_at', { mode: 'timestamp_ms' }),
  },
  (table) => [
    foreignKey({ name: 'list_items_list_fk', columns: [table.listId, table.workspaceId], foreignColumns: [lists.id, lists.workspaceId] }),
    index('list_items_list_idx').on(table.listId, table.deletedAt, table.position),
    check('list_items_id_uuid', sql`length(${table.id}) = 36`),
    check('list_items_title_present', sql`length(trim(${table.title})) > 0 and length(${table.title}) <= 120`),
    check('list_items_quantity_format', sql`${table.quantity} is null or (length(${table.quantity}) between 1 and 9 and ${table.quantity} not glob '*[^0-9.]*')`),
    check('list_items_unit_bounded', sql`${table.unit} is null or (length(trim(${table.unit})) > 0 and length(${table.unit}) <= 16)`),
    check('list_items_revision_positive', sql`${table.revision} >= 1`),
    check('list_items_position_valid', sql`${table.position} >= 0`),
    check(
      'list_items_check_consistent',
      sql`(${table.checkedAt} is null) = (${table.checkedByUserId} is null) and (${table.checkedAt} is null) = (${table.checkedByDisplayName} is null)`,
    ),
  ],
);

/**
 * Document files (16.1): one uploaded file of a Workspace. The bytes — the original, exactly as
 * uploaded — live in the document store, named by `sha256`. Everything about the file is immutable
 * (trigger in migration 0027); only the progress of its previews changes. Identical content uploaded
 * twice is two rows (each with its own name and uploader) and is charged once.
 */
export const documentFiles = sqliteTable(
  'document_files',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    sha256: text('sha256').notNull(),
    bytes: integer('bytes').notNull(),
    /** Identified from the content, never from the name or a declared type. */
    format: text('format', { enum: DOCUMENT_FILE_FORMATS }).notNull(),
    /** The name it was uploaded with: data only, never a path. */
    originalName: text('original_name').notNull(),
    /** Pages of a PDF (NULL when password-protected); 1 for an image. */
    pageCount: integer('page_count'),
    width: integer('width'),
    height: integer('height'),
    encrypted: integer('encrypted', { mode: 'boolean' }).notNull().default(false),
    activeContent: integer('active_content', { mode: 'boolean' }).notNull().default(false),
    previewState: text('preview_state', { enum: PREVIEW_STATES }).notNull(),
    previewAttempts: integer('preview_attempts').notNull().default(0),
    uploadedByUserId: text('uploaded_by_user_id')
      .notNull()
      .references(() => users.id),
    uploadedByDisplayName: text('uploaded_by_display_name').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [
    index('document_files_workspace_idx').on(table.workspaceId, table.sha256),
    index('document_files_sha_idx').on(table.sha256),
    index('document_files_preview_idx').on(table.previewState, table.createdAt),
    // Lets later tables reference (file, workspace) together: a file never sits in another Workspace's Document.
    uniqueIndex('document_files_id_workspace_unique').on(table.id, table.workspaceId),
    check('document_files_id_uuid', sql`length(${table.id}) = 36`),
    check('document_files_sha_format', sql`length(${table.sha256}) = 64 and ${table.sha256} not glob '*[^0-9a-f]*'`),
    check('document_files_bytes_bounded', sql`${table.bytes} between 1 and 100000000`),
    check('document_files_format_valid', oneOf('format', DOCUMENT_FILE_FORMATS)),
    check('document_files_name_present', sql`length(trim(${table.originalName})) > 0 and length(${table.originalName}) <= 255`),
    check('document_files_pages_bounded', sql`${table.pageCount} is null or ${table.pageCount} >= 1`),
    check('document_files_size_consistent', sql`(${table.width} is null) = (${table.height} is null) and (${table.width} is null or (${table.width} >= 1 and ${table.height} >= 1))`),
    check('document_files_preview_state_valid', oneOf('preview_state', PREVIEW_STATES)),
    check('document_files_attempts_valid', sql`${table.previewAttempts} >= 0`),
  ],
);

/**
 * Derived files of a document file (16.1): preview pages and the thumbnail — inert, metadata-free
 * JPEGs in the document store. They can be made again from the original and are never the original.
 */
export const documentFileDerivatives = sqliteTable(
  'document_file_derivatives',
  {
    fileId: text('file_id')
      .notNull()
      .references(() => documentFiles.id),
    kind: text('kind', { enum: DERIVATIVE_KINDS }).notNull(),
    /** 0-based page of the original; 0 for an image and for the thumbnail. */
    page: integer('page').notNull(),
    sha256: text('sha256').notNull(),
    bytes: integer('bytes').notNull(),
    width: integer('width').notNull(),
    height: integer('height').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.fileId, table.kind, table.page] }),
    index('document_file_derivatives_sha_idx').on(table.sha256),
    check('document_file_derivatives_kind_valid', oneOf('kind', DERIVATIVE_KINDS)),
    check('document_file_derivatives_page_bounded', sql`${table.page} between 0 and 499`),
    check('document_file_derivatives_sha_format', sql`length(${table.sha256}) = 64 and ${table.sha256} not glob '*[^0-9a-f]*'`),
    check('document_file_derivatives_bytes_positive', sql`${table.bytes} >= 1`),
    check('document_file_derivatives_size_bounded', sql`${table.width} between 1 and 2400 and ${table.height} between 1 and 2400`),
  ],
);

/**
 * Optional tools of a Workspace (16.2): switched on by a Workspace admin. No row = not enabled.
 * Disabling keeps the row (and all data of the tool); enabling again shows the same data.
 */
export const workspaceTools = sqliteTable(
  'workspace_tools',
  {
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    tool: text('tool', { enum: WORKSPACE_TOOLS }).notNull(),
    enabled: integer('enabled', { mode: 'boolean' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
    updatedByUserId: text('updated_by_user_id')
      .notNull()
      .references(() => users.id),
  },
  (table) => [primaryKey({ columns: [table.workspaceId, table.tool] }), check('workspace_tools_tool_valid', oneOf('tool', WORKSPACE_TOOLS))],
);

/**
 * Folders of Documents (16.2): a tree per Workspace. `name_key` is the name as siblings are compared
 * (NFKC, lower case); live siblings are unique by it. Deleting sets the `deleted_*` columns (Trash):
 * `deleted_with_folder_id` names the Folder whose deletion took this one along (its own id for the
 * Folder that was deleted itself), so restoring that Folder brings back exactly what went with it.
 * A cycle is impossible: the application checks inside the transaction and a trigger refuses it.
 */
export const documentFolders = sqliteTable(
  'document_folders',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    parentId: text('parent_id'),
    name: text('name').notNull(),
    nameKey: text('name_key').notNull(),
    revision: integer('revision').notNull().default(1),
    createdByUserId: text('created_by_user_id')
      .notNull()
      .references(() => users.id),
    createdByDisplayName: text('created_by_display_name').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
    deletedAt: integer('deleted_at', { mode: 'timestamp_ms' }),
    deletedByUserId: text('deleted_by_user_id').references(() => users.id),
    deletedByDisplayName: text('deleted_by_display_name'),
    deletedWithFolderId: text('deleted_with_folder_id'),
  },
  (table) => [
    // Lets children and Documents reference (folder, workspace) together: nothing sits in another Workspace's Folder.
    uniqueIndex('document_folders_id_workspace_unique').on(table.id, table.workspaceId),
    foreignKey({ name: 'document_folders_parent_fk', columns: [table.parentId, table.workspaceId], foreignColumns: [table.id, table.workspaceId] }),
    // Live siblings are unique by name: `document_folders_sibling_name_unique`, an expression index written by hand in migration 0028.
    index('document_folders_parent_idx').on(table.workspaceId, table.parentId),
    index('document_folders_deleted_with_idx').on(table.deletedWithFolderId),
    check('document_folders_id_uuid', sql`length(${table.id}) = 36`),
    check('document_folders_name_present', sql`length(trim(${table.name})) > 0 and length(${table.name}) <= 80 and instr(${table.name}, '/') = 0`),
    check('document_folders_not_own_parent', sql`${table.parentId} is null or ${table.parentId} <> ${table.id}`),
    check('document_folders_revision_positive', sql`${table.revision} >= 1`),
    check(
      'document_folders_deletion_consistent',
      sql`(${table.deletedAt} is null) = (${table.deletedByUserId} is null) and (${table.deletedAt} is null) = (${table.deletedByDisplayName} is null) and (${table.deletedAt} is null) = (${table.deletedWithFolderId} is null)`,
    ),
  ],
);

/** A Workspace's own document types (16.2). A retired type stays on the Documents that have it and is not offered for new ones. */
export const documentTypes = sqliteTable(
  'document_types',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    name: text('name').notNull(),
    nameKey: text('name_key').notNull(),
    retiredAt: integer('retired_at', { mode: 'timestamp_ms' }),
    createdByUserId: text('created_by_user_id')
      .notNull()
      .references(() => users.id),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [
    uniqueIndex('document_types_id_workspace_unique').on(table.id, table.workspaceId),
    uniqueIndex('document_types_name_unique').on(table.workspaceId, table.nameKey).where(sql`${table.retiredAt} is null`),
    check('document_types_id_uuid', sql`length(${table.id}) = 36`),
    check('document_types_name_present', sql`length(trim(${table.name})) > 0 and length(${table.name}) <= 60`),
  ],
);

/**
 * Documents (16.2): one record with ordered files (`document_pages`). "Uploaded" (`created_*`) never
 * changes (trigger in migration 0028); every edit sets "last modified" (`updated_*`). Trash as for Folders;
 * a Document deleted by itself has `deleted_with_folder_id` NULL.
 */
export const documents = sqliteTable(
  'documents',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    folderId: text('folder_id'),
    title: text('title').notNull(),
    /** A built-in type by key, or … */
    typeKey: text('type_key', { enum: BUILT_IN_DOCUMENT_TYPES }),
    /** … one of the Workspace's own types. At most one of the two. */
    typeId: text('type_id'),
    /** The date on the paper, `YYYY-MM-DD`. */
    documentDate: text('document_date'),
    year: integer('year'),
    notes: text('notes').notNull().default(''),
    tags: text('tags', { mode: 'json' }).$type<string[]>().notNull().default(sql`'[]'`),
    /**
     * Derived for finding (16.3), written with every change of title, notes or tags: the folded title
     * (sort key), the folded tags (tag filter) and everything a search looks at (`documentSearchText`).
     * NULL only on rows from before migration 0029 until `migrate` has filled them; a trigger refuses
     * new rows without them.
     */
    titleKey: text('title_key'),
    tagKeys: text('tag_keys', { mode: 'json' }).$type<string[]>(),
    searchText: text('search_text'),
    revision: integer('revision').notNull().default(1),
    createdByUserId: text('created_by_user_id')
      .notNull()
      .references(() => users.id),
    createdByDisplayName: text('created_by_display_name').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedByUserId: text('updated_by_user_id')
      .notNull()
      .references(() => users.id),
    updatedByDisplayName: text('updated_by_display_name').notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
    deletedAt: integer('deleted_at', { mode: 'timestamp_ms' }),
    deletedByUserId: text('deleted_by_user_id').references(() => users.id),
    deletedByDisplayName: text('deleted_by_display_name'),
    deletedWithFolderId: text('deleted_with_folder_id'),
  },
  (table) => [
    uniqueIndex('documents_id_workspace_unique').on(table.id, table.workspaceId),
    foreignKey({ name: 'documents_folder_fk', columns: [table.folderId, table.workspaceId], foreignColumns: [documentFolders.id, documentFolders.workspaceId] }),
    foreignKey({ name: 'documents_type_fk', columns: [table.typeId, table.workspaceId], foreignColumns: [documentTypes.id, documentTypes.workspaceId] }),
    index('documents_folder_idx').on(table.workspaceId, table.folderId, table.deletedAt),
    index('documents_deleted_with_idx').on(table.deletedWithFolderId),
    // One per sort order of the listing (16.3), over the Documents that are not in Trash.
    index('documents_uploaded_idx').on(table.workspaceId, table.createdAt, table.id).where(sql`${table.deletedAt} is null`),
    index('documents_modified_idx').on(table.workspaceId, table.updatedAt, table.id).where(sql`${table.deletedAt} is null`),
    index('documents_date_idx').on(table.workspaceId, table.documentDate, table.id).where(sql`${table.deletedAt} is null`),
    index('documents_title_idx').on(table.workspaceId, table.titleKey, table.id).where(sql`${table.deletedAt} is null`),
    check('documents_id_uuid', sql`length(${table.id}) = 36`),
    check('documents_title_present', sql`length(trim(${table.title})) > 0 and length(${table.title}) <= 200`),
    check('documents_type_single', sql`${table.typeKey} is null or ${table.typeId} is null`),
    check('documents_type_key_valid', sql.raw(`type_key is null or type_key in (${BUILT_IN_DOCUMENT_TYPES.map((key) => `'${key}'`).join(', ')})`)),
    check('documents_date_format', sql`${table.documentDate} is null or ${table.documentDate} glob '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'`),
    check('documents_year_bounded', sql`${table.year} is null or ${table.year} between 1900 and 2200`),
    check('documents_notes_bounded', sql`length(${table.notes}) <= 4000`),
    check('documents_tags_array', sql`json_valid(${table.tags}) and json_type(${table.tags}) = 'array' and json_array_length(${table.tags}) <= 10`),
    check('documents_revision_positive', sql`${table.revision} >= 1`),
    check(
      'documents_deletion_consistent',
      sql`(${table.deletedAt} is null) = (${table.deletedByUserId} is null) and (${table.deletedAt} is null) = (${table.deletedByDisplayName} is null)`,
    ),
  ],
);

/**
 * The ordered files (pages) of a Document. A file belongs to at most one Document, and — through the
 * composite foreign keys — always to one of its own Workspace. This table is what makes an uploaded
 * file permanent: a file that is on no page is removed by housekeeping after the grace period.
 */
export const documentPages = sqliteTable(
  'document_pages',
  {
    documentId: text('document_id').notNull(),
    workspaceId: text('workspace_id').notNull(),
    position: integer('position').notNull(),
    fileId: text('file_id').notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.documentId, table.position] }),
    uniqueIndex('document_pages_file_unique').on(table.fileId),
    foreignKey({ name: 'document_pages_document_fk', columns: [table.documentId, table.workspaceId], foreignColumns: [documents.id, documents.workspaceId] }),
    foreignKey({ name: 'document_pages_file_fk', columns: [table.fileId, table.workspaceId], foreignColumns: [documentFiles.id, documentFiles.workspaceId] }),
    check('document_pages_position_bounded', sql`${table.position} between 0 and 49`),
  ],
);

/**
 * Links (16.5, HT8): one typed table for references between two records of a Workspace. `from` is a
 * Document so far; `to` a Document ("related", stored once with the smaller id first), a Procedure or a
 * Schedule. SQLite cannot declare a foreign key to "one of several tables", so **triggers in migration
 * 0031** make sure both ends exist in the same Workspace when a Link is added — a cross-Workspace Link
 * cannot exist. A Document that is deleted for good leaves its end marked as gone (when, by whom)
 * instead of taking the Link away: the other record still says that something was linked.
 */
/**
 * Contacts (16.6): people and organisations of a Workspace. Not Users: nothing here grants access.
 * `emails` and `phones` are what is shown; `contact_keys` is what Contacts are compared by.
 */
export const contacts = sqliteTable(
  'contacts',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    name: text('name').notNull(),
    organisation: text('organisation').notNull().default(''),
    category: text('category').notNull().default(''),
    emails: text('emails', { mode: 'json' }).$type<{ value: string; label: string }[]>().notNull().default(sql`'[]'`),
    phones: text('phones', { mode: 'json' }).$type<{ value: string; label: string }[]>().notNull().default(sql`'[]'`),
    address: text('address').notNull().default(''),
    website: text('website').notNull().default(''),
    notes: text('notes').notNull().default(''),
    /** Derived, written with every change: the folded name (order), the folded category (filter), and everything a search looks at. */
    sortKey: text('sort_key').notNull(),
    categoryKey: text('category_key').notNull().default(''),
    searchText: text('search_text').notNull(),
    revision: integer('revision').notNull().default(1),
    createdByUserId: text('created_by_user_id')
      .notNull()
      .references(() => users.id),
    createdByDisplayName: text('created_by_display_name').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedByUserId: text('updated_by_user_id')
      .notNull()
      .references(() => users.id),
    updatedByDisplayName: text('updated_by_display_name').notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
    deletedAt: integer('deleted_at', { mode: 'timestamp_ms' }),
    deletedByUserId: text('deleted_by_user_id').references(() => users.id),
    deletedByDisplayName: text('deleted_by_display_name'),
  },
  (table) => [
    uniqueIndex('contacts_id_workspace_unique').on(table.id, table.workspaceId),
    index('contacts_name_idx').on(table.workspaceId, table.sortKey, table.id).where(sql`${table.deletedAt} is null`),
    index('contacts_trash_idx').on(table.workspaceId, table.deletedAt),
    check('contacts_id_uuid', sql`length(${table.id}) = 36`),
    check('contacts_name_present', sql`length(trim(${table.name})) > 0 and length(${table.name}) <= 200`),
    check('contacts_text_bounded', sql`length(${table.organisation}) <= 200 and length(${table.category}) <= 60 and length(${table.address}) <= 500 and length(${table.notes}) <= 4000`),
    // Whatever wrote the row: a website is an http(s) address or nothing.
    check('contacts_website_http', sql`${table.website} = '' or (length(${table.website}) <= 500 and (${table.website} like 'http://%' or ${table.website} like 'https://%'))`),
    check('contacts_emails_array', sql`json_valid(${table.emails}) and json_type(${table.emails}) = 'array' and json_array_length(${table.emails}) <= 10`),
    check('contacts_phones_array', sql`json_valid(${table.phones}) and json_type(${table.phones}) = 'array' and json_array_length(${table.phones}) <= 10`),
    check('contacts_revision_positive', sql`${table.revision} >= 1`),
    check('contacts_deletion_consistent', sql`(${table.deletedAt} is null) = (${table.deletedByUserId} is null) and (${table.deletedAt} is null) = (${table.deletedByDisplayName} is null)`),
  ],
);

/** What a Contact is compared by for possible duplicates: each email address, each phone number without formatting, its name key. */
export const contactKeys = sqliteTable(
  'contact_keys',
  {
    contactId: text('contact_id').notNull(),
    workspaceId: text('workspace_id').notNull(),
    kind: text('kind', { enum: CONTACT_KEY_KINDS }).notNull(),
    key: text('key').notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.contactId, table.kind, table.key] }),
    foreignKey({ name: 'contact_keys_contact_fk', columns: [table.contactId, table.workspaceId], foreignColumns: [contacts.id, contacts.workspaceId] }),
    index('contact_keys_lookup_idx').on(table.workspaceId, table.kind, table.key),
    check('contact_keys_kind_valid', oneOf('kind', CONTACT_KEY_KINDS)),
  ],
);

/**
 * MaintenanceRecords (16.7): planned or done work with one of four statuses. The status is set by
 * people only — nothing here references a Run, and no Run, Occurrence or Reminder writes to this table.
 */
export const maintenanceRecords = sqliteTable(
  'maintenance_records',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    title: text('title').notNull(),
    category: text('category').notNull().default(''),
    /** When the work is planned for (`YYYY-MM-DD`), or none. */
    date: text('date'),
    status: text('status', { enum: MAINTENANCE_STATUSES }).notNull().default('PLANNED'),
    /** The day the work was completed: set exactly while the status is COMPLETED. */
    completedOn: text('completed_on'),
    description: text('description').notNull().default(''),
    /** The responsible Contact, by id. Not a foreign key: a Contact deleted for good leaves "a deleted contact" here. */
    contactId: text('contact_id'),
    /** A cost as written — decimal text, never a float — with its ISO 4217 currency; both or neither. */
    costAmount: text('cost_amount'),
    costCurrency: text('cost_currency'),
    /** Derived, written with every change: the folded category (filter), the day the record is filed under (List order, year filter), what a search looks at. */
    categoryKey: text('category_key').notNull().default(''),
    sortDate: text('sort_date').notNull(),
    searchText: text('search_text').notNull(),
    revision: integer('revision').notNull().default(1),
    createdByUserId: text('created_by_user_id')
      .notNull()
      .references(() => users.id),
    createdByDisplayName: text('created_by_display_name').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedByUserId: text('updated_by_user_id')
      .notNull()
      .references(() => users.id),
    updatedByDisplayName: text('updated_by_display_name').notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
    deletedAt: integer('deleted_at', { mode: 'timestamp_ms' }),
    deletedByUserId: text('deleted_by_user_id').references(() => users.id),
    deletedByDisplayName: text('deleted_by_display_name'),
  },
  (table) => [
    uniqueIndex('maintenance_records_id_workspace_unique').on(table.id, table.workspaceId),
    index('maintenance_records_list_idx').on(table.workspaceId, table.sortDate, table.id).where(sql`${table.deletedAt} is null`),
    index('maintenance_records_board_idx').on(table.workspaceId, table.status, table.sortDate).where(sql`${table.deletedAt} is null`),
    index('maintenance_records_contact_idx').on(table.workspaceId, table.contactId),
    check('maintenance_records_id_uuid', sql`length(${table.id}) = 36`),
    check('maintenance_records_title_present', sql`length(trim(${table.title})) > 0 and length(${table.title}) <= 200`),
    check('maintenance_records_text_bounded', sql`length(${table.category}) <= 60 and length(${table.description}) <= 4000`),
    check('maintenance_records_status_valid', oneOf('status', MAINTENANCE_STATUSES)),
    check('maintenance_records_dates_format', sql`(${table.date} is null or ${table.date} glob '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]') and (${table.completedOn} is null or ${table.completedOn} glob '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]') and ${table.sortDate} glob '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'`),
    // Completed is unmistakable: a completion date exactly while the status says so.
    check('maintenance_records_completion_consistent', sql`(${table.status} = 'COMPLETED') = (${table.completedOn} is not null)`),
    check('maintenance_records_cost_consistent', sql`(${table.costAmount} is null) = (${table.costCurrency} is null)`),
    check('maintenance_records_cost_shape', sql`${table.costAmount} is null or (length(${table.costAmount}) <= 16 and ${table.costAmount} not glob '*[^0-9.]*' and length(${table.costCurrency}) = 3 and ${table.costCurrency} not glob '*[^A-Z]*')`),
    check('maintenance_records_revision_positive', sql`${table.revision} >= 1`),
    check('maintenance_records_deletion_consistent', sql`(${table.deletedAt} is null) = (${table.deletedByUserId} is null) and (${table.deletedAt} is null) = (${table.deletedByDisplayName} is null)`),
  ],
);

export const links = sqliteTable(
  'links',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    fromType: text('from_type').notNull(),
    fromId: text('from_id').notNull(),
    toType: text('to_type').notNull(),
    toId: text('to_id').notNull(),
    createdByUserId: text('created_by_user_id')
      .notNull()
      .references(() => users.id),
    createdByDisplayName: text('created_by_display_name').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    fromGoneAt: integer('from_gone_at', { mode: 'timestamp_ms' }),
    fromGoneByDisplayName: text('from_gone_by_display_name'),
    toGoneAt: integer('to_gone_at', { mode: 'timestamp_ms' }),
    toGoneByDisplayName: text('to_gone_by_display_name'),
  },
  (table) => [
    uniqueIndex('links_pair_unique').on(table.workspaceId, table.fromType, table.fromId, table.toType, table.toId),
    index('links_to_idx').on(table.workspaceId, table.toType, table.toId),
    check('links_id_uuid', sql`length(${table.id}) = 36`),
    check('links_ends_differ', sql`${table.fromType} <> ${table.toType} or ${table.fromId} <> ${table.toId}`),
    check('links_from_gone_consistent', sql`(${table.fromGoneAt} is null) = (${table.fromGoneByDisplayName} is null)`),
    check('links_to_gone_consistent', sql`(${table.toGoneAt} is null) = (${table.toGoneByDisplayName} is null)`),
  ],
);

/**
 * A Document version retained for a Run (16.5, H10): the Document's details as they were when it was
 * linked, and — in `run_document_files` — its files in page order. Immutable (triggers in migration
 * 0031); it can only be removed while the Run is ACTIVE. Kept beside the Run: nothing in the Run's own
 * tables is touched. `source_document_id` is where it came from — not a foreign key, because the
 * source may be deleted for good while the version stays.
 */
export const runDocuments = sqliteTable(
  'run_documents',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    runId: text('run_id')
      .notNull()
      .references(() => runs.id),
    sourceDocumentId: text('source_document_id').notNull(),
    sourceRevision: integer('source_revision').notNull(),
    title: text('title').notNull(),
    typeKey: text('type_key'),
    /** The name of a Workspace's own type at the time. */
    typeName: text('type_name'),
    documentDate: text('document_date'),
    year: integer('year'),
    notes: text('notes').notNull().default(''),
    tags: text('tags', { mode: 'json' }).$type<string[]>().notNull().default(sql`'[]'`),
    linkedByUserId: text('linked_by_user_id')
      .notNull()
      .references(() => users.id),
    linkedByDisplayName: text('linked_by_display_name').notNull(),
    linkedAt: integer('linked_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [
    uniqueIndex('run_documents_source_unique').on(table.runId, table.sourceDocumentId),
    index('run_documents_source_idx').on(table.workspaceId, table.sourceDocumentId),
    check('run_documents_id_uuid', sql`length(${table.id}) = 36`),
  ],
);

/** The files of a retained Document version, in page order. This reference keeps the files from housekeeping. */
export const runDocumentFiles = sqliteTable(
  'run_document_files',
  {
    runDocumentId: text('run_document_id')
      .notNull()
      .references(() => runDocuments.id),
    workspaceId: text('workspace_id').notNull(),
    position: integer('position').notNull(),
    fileId: text('file_id').notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.runDocumentId, table.position] }),
    index('run_document_files_file_idx').on(table.fileId),
    foreignKey({ name: 'run_document_files_file_fk', columns: [table.fileId, table.workspaceId], foreignColumns: [documentFiles.id, documentFiles.workspaceId] }),
  ],
);

/**
 * The permanent note left when a Workspace admin removes a Document version from a **finished** Run
 * (16.5, P4): who removed it, when and why, and when it had been linked — **nothing of the document**
 * (no title, no details, no file reference). Never changed or deleted (triggers in migration 0032).
 * `run_document_id` is the removed row's id: its presence is what lets that row be deleted.
 */
export const runDocumentRemovals = sqliteTable(
  'run_document_removals',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    runId: text('run_id')
      .notNull()
      .references(() => runs.id),
    runDocumentId: text('run_document_id').notNull(),
    reason: text('reason').notNull(),
    files: integer('files').notNull(),
    linkedByDisplayName: text('linked_by_display_name').notNull(),
    linkedAt: integer('linked_at', { mode: 'timestamp_ms' }).notNull(),
    removedByUserId: text('removed_by_user_id')
      .notNull()
      .references(() => users.id),
    removedByDisplayName: text('removed_by_display_name').notNull(),
    removedAt: integer('removed_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [
    uniqueIndex('run_document_removals_document_unique').on(table.runDocumentId),
    index('run_document_removals_run_idx').on(table.workspaceId, table.runId),
    check('run_document_removals_id_uuid', sql`length(${table.id}) = 36`),
    check('run_document_removals_reason_present', sql`length(trim(${table.reason})) > 0 and length(${table.reason}) <= 500`),
  ],
);
