// Drizzle schema. Every change ships with a committed migration generated by `pnpm db:generate`.
//
// Auth-related tables follow Better Auth's core schema: Drizzle *property* names are the
// Better Auth field names (e.g. `name`, `emailVerified`), while *column* names are snake_case.
import { sql } from 'drizzle-orm';
import { check, integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';
import { USER_STATUSES } from '@vergissmeinnicht/domain';

const timestampMs = (column: string) =>
  integer(column, { mode: 'timestamp_ms' })
    .notNull()
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`);

/**
 * Internal Users. `id` is the stable internal identity; login methods (password, TOTP,
 * future Apple/GitHub) are linked to it by separate tables and never replace it.
 */
export const users = sqliteTable(
  'users',
  {
    id: text('id').primaryKey(),
    /** Display name (Better Auth field `name`). */
    name: text('display_name').notNull(),
    /** Normalized email; see `normalizeEmail` in the domain package. */
    email: text('email').notNull().unique(),
    emailVerified: integer('email_verified', { mode: 'boolean' }).notNull().default(false),
    /** Better Auth core field. Not rendered anywhere until a reviewed use exists (see security.md §5). */
    image: text('image'),
    status: text('status', { enum: USER_STATUSES }).notNull().default('ACTIVE'),
    createdAt: timestampMs('created_at'),
    updatedAt: timestampMs('updated_at'),
  },
  (table) => [
    // Defense in depth behind application-side validation.
    check('users_id_uuid', sql`length(${table.id}) = 36`),
    check('users_email_normalized', sql`${table.email} = lower(trim(${table.email})) and length(${table.email}) <= 254`),
    check('users_display_name_present', sql`length(trim(${table.name})) > 0`),
    check(
      'users_status_valid',
      sql.raw(`status in (${USER_STATUSES.map((status) => `'${status}'`).join(', ')})`),
    ),
  ],
);
