#!/usr/bin/env bash
# Installs and starts the local test environment (idempotent: running it again after a reboot or
# `uninstall.sh --stop` just starts the server again and keeps the demo data).
#
#   test-env/install.sh
#
# See test-env/README.md.
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
cd "$REPO_ROOT"

# --- Preflight ----------------------------------------------------------------------------
for tool in node curl openssl; do
  command -v "$tool" >/dev/null || die "$tool is required but not installed."
done
node_major="$(node -p 'process.versions.node.split(".")[0]')"
((node_major >= 24)) || die "Node.js 24 or newer is required (found $(node -v))."

if [[ -n "$(server_pid)" ]] && server_healthy; then
  ok "Test environment is already running at $TEST_ORIGIN"
  [[ -f "$CREDENTIALS_FILE" ]] && cat "$CREDENTIALS_FILE"
  exit 0
fi
if curl -s -m 2 -o /dev/null "$TEST_ORIGIN" 2>/dev/null; then
  die "Port $TEST_PORT is already in use by another program. Set VMN_TEST_PORT to use a different port."
fi

# --- Dependencies and build ---------------------------------------------------------------
if [[ ! -d node_modules ]]; then
  command -v pnpm >/dev/null || die "Dependencies are not installed and pnpm is missing. Install it with: npm install -g pnpm@12.6.0"
  info "Installing dependencies (pnpm install --frozen-lockfile)"
  pnpm install --frozen-lockfile
fi
info "Building the web app"
(cd apps/web && ./node_modules/.bin/vite build --logLevel warn)

# --- Configuration (created once, secrets never leave .var/test-env) ----------------------
mkdir -p "$STATE_DIR"
chmod 700 "$STATE_DIR"
if [[ ! -f "$ENV_FILE" ]]; then
  info "Generating test configuration and secrets"
  (
    umask 077
    cat >"$ENV_FILE" <<EOF
# Generated by test-env/install.sh — local test environment only. Removed by uninstall.sh.
HOST=127.0.0.1
PORT=$TEST_PORT
PUBLIC_ORIGIN=$TEST_ORIGIN
DATABASE_PATH=$STATE_DIR/vergissmeinnicht.sqlite
AUTH_SECRET=$(openssl rand -base64 32)
DATA_ENCRYPTION_KEY=$(openssl rand -base64 32)
LOG_LEVEL=info
SMTP_HOST=127.0.0.1
SMTP_PORT=1025
SMTP_SECURITY=none
MAIL_FROM_ADDRESS=noreply@vergissmeinnicht.test
MAIL_FROM_NAME=VergissMeinNicht (test)
EOF
  )
fi

# --- Mailpit (reused if one is already running, e.g. from `docker compose -f compose.dev.yml`) ---
if mailpit_running; then
  ok "Using the Mailpit that is already running ($MAILPIT_UI)"
else
  command -v docker >/dev/null || die "Docker is required to start Mailpit (the email inbox for invitations)."
  info "Starting Mailpit"
  compose up -d --quiet-pull >/dev/null 2>&1 || die "Could not start Mailpit (is Docker running, are ports 1025/8025 free?)"
  touch "$MAILPIT_MARKER"
  for _ in $(seq 1 30); do
    mailpit_running && break
    sleep 1
  done
  mailpit_running || die "Mailpit did not start. Check: docker compose -p $COMPOSE_PROJECT -f compose.dev.yml logs"
fi

# --- Database and server ------------------------------------------------------------------
run_node() { NODE_ENV=production node --env-file="$ENV_FILE" "$@"; }

info "Applying database migrations"
run_node packages/database/src/migrate.ts >/dev/null

info "Starting the server on $TEST_ORIGIN"
: >>"$LOG_FILE"
chmod 600 "$LOG_FILE"
NODE_ENV=production setsid node --env-file="$ENV_FILE" apps/server/src/main.ts >>"$LOG_FILE" 2>&1 </dev/null &
echo $! >"$PID_FILE"
for _ in $(seq 1 30); do
  server_healthy && break
  sleep 0.5
done
server_healthy || die "The server did not start. See $LOG_FILE"

# --- Demo data (first install only) -------------------------------------------------------
if [[ ! -f "$SEEDED_MARKER" ]]; then
  password="$(openssl rand -base64 18 | tr -d '/+=')-test"
  info "Creating demo accounts and Workspaces"
  bootstrap_output="$(run_node apps/server/src/cli/admin-bootstrap.ts --email admin@vmn.test)" ||
    die "Bootstrap failed. A server admin may already exist; run uninstall.sh and install again."
  bootstrap_link="$(grep -oE "$TEST_ORIGIN/invite/[A-Za-z0-9_-]+" <<<"$bootstrap_output" | head -1)"
  [[ -n "$bootstrap_link" ]] || die "Could not read the bootstrap link."

  VMN_TEST_ORIGIN="$TEST_ORIGIN" VMN_TEST_MAILPIT="$MAILPIT_UI" VMN_TEST_PASSWORD="$password" \
    VMN_TEST_BOOTSTRAP_LINK="$bootstrap_link" node test-env/seed.ts ||
    die "Creating demo data failed. Run test-env/uninstall.sh and install again."

  (
    umask 077
    cat >"$CREDENTIALS_FILE" <<EOF

  App:      $TEST_ORIGIN
  Mailpit:  $MAILPIT_UI   (invitation and recovery emails)
  Password for every demo account:  $password

  Account             Server admin   "Demo Household"   "Demo Office"
  admin@vmn.test      yes            ADMIN              ADMIN
  editor@vmn.test     -              EDITOR             -
  user@vmn.test       -              USER               -
  guest@vmn.test      -              GUEST              -
  outsider@vmn.test   -              -                  USER

  Use a private window or a second browser profile to be signed in as two people at once.
  Server log: $LOG_FILE
EOF
  )
  touch "$SEEDED_MARKER"
fi

ok "Test environment is running"
cat "$CREDENTIALS_FILE"
